### ISSUE TITLE
Test Impact collector not working side by side with code coverage collector

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vstest#1010]
## Description
With the implementation of test impact collector available, I was trying to run both the test impact and code coverage collectors together. Provided the switch /collect:"Code Coverage" for enabling and code collector and enabled test impact collector in the run settings. This caused only the code coverage collector to run and test impact collector was ignored. When I provide both the collectors in run settings file, then both collectors work fine and produce the desired results.

## Steps to reproduce
> Create TPv2 based test project.
> Run from command line using TPv2 vstest console and enable code coverage from command line switch and any other collector from run settings file.

## Expected behavior
> Output from both the collectors should be generated.

## Actual behavior
> Only code coverage collector output is generated

**Comment by harshjain2** [comment]
This is expected behavior.
https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#enabledisable-a-datacollector

If you want both the code coverage and test impact data collector to work, you need to provide two switches ` /collect:"Code Coverage"` and `/collect:"Test Impact"`
If you are using RunSettings and your RunSettings have Test Impact datacollector's settings, it will be picked up. Otherwise, default runsettings will be used.

**Comment by prawalagarwal** [comment]
Thanks. Closing the issue.
