### ISSUE TITLE
Microsoft.TestPlatform.CommunicationUtilities references Newtonsoft.Json 9.0.0.0

### ISSUE THREAD

**Issue by tannergooding** [Microsoft/vstest#121]
The Microsoft.TestPlatform.CommunicationUtilities binary directly references Newtonsoft.Json v9.0.0 while VS has standardized on v8.0.3.

Looking at the project, it references v8.0.3, so the project reference to v9 is indirect and NuGet or MSBuild resolves it to be v9 when the compilation actually occurs (causing the binary to have the direct reference to v9).

**Comment by drognanar** [comment]
It seems that this issue is happening again after PR #727 was merged.
The portable CommunicationUtilities project is now explicitly referencing Newtonsoft.Json 9.0, while the TranslationLayer package is still referencing 8.0.3.

CommunicationUtilities: https://github.com/Microsoft/vstest/blob/18ca783e16b1e66f3b7e70a6f3af23f4507b9df4/src/Microsoft.TestPlatform.CommunicationUtilities/Microsoft.TestPlatform.CommunicationUtilities.csproj#L26
TranslationLayer: https://github.com/Microsoft/vstest/blob/18ca783e16b1e66f3b7e70a6f3af23f4507b9df4/src/package/nuspec/TestPlatform.TranslationLayer.nuspec#L33

**Comment by codito** [comment]
Thanks @drognanar, created a PR for this.

**Comment by tannergooding** [comment]
@codito, @drognanar. This might actually be ok. I forwarded the relevant e-mail to @ManishJayaswal, but it looks like we may be moving forward anyways.
