### ISSUE TITLE
Microsoft.TestPlatform nuget package throws PathTooLongException 

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#1214]
## Description
We have recently introduced Microsoft.TestPlatform nuget package [here](https://github.com/Microsoft/vstest/pull/1211). 
Because of long path structure of this package, users of this nuget package might face PathTooLongException.

It is required to break `Common7\IDE\...` dependency and have a relatively flat structure.

## Workaround
Keep the Microsoft.Testplatform nuget package at the root folder of directory (D:\Microsoft.TestPlatfrom, etc.)

**Comment by pvlakshm** [comment]
I don't think end users can extract to the ```...\Common7\IDE\...``` folder. And no matter how short our package name, if the user were to extract it to a deep folder structure (s)he could still face the PathTooLongException, right?

I think we can live with this.

**Comment by smadala** [comment]
@pvlakshm Following is path if I install the package by default `C:\Users\samadala\.nuget\packages\Microsoft.TestPlatform\15.5.0-preview-20170810-02\tools\net451\Common7\IDE\Extensions\TestPlatform\Extensions\CppUnitFramework\Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.x64.dll.manifest` which is `240` character.
If I change the nuget package folder to %temp% it is 260 character. `C:\Users\samadala\AppData\Local\Temp\.nuget\packages\Microsoft.TestPlatform\15.5.0-preview-20170810-02\tools\net451\Common7\IDE\Extensions\TestPlatform\Extensions\CppUnitFramework\Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.x64.dll.manifest
`
There was live site issue with cloudbuild due to this very long layout last month. We should consider to break this long layout.

**Comment by smadala** [comment]
https://github.com/Microsoft/vstest/pull/1259 unblocks cloudbuild team. 
/cc @acesiddhu  JFYI.
