### ISSUE TITLE
VS adds 'Service' item to csproj

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vstest#1267]
Using Visual Studio 2017 version 15.5 Preview 2, I'm still encountering #409 every time I open a solution with test code. The situation appears to not be affecting one project using xUnit, but is affecting another project using MSTest v1.

**Comment by livarcocc** [comment]
I saw this as well: https://github.com/dotnet/cli/pull/7964/files#diff-cbf60a130b25cbf65c788d13689daacbR30

**Comment by sharwell** [comment]
It sounds like the previous fix attempted to look for a project capability in order to suppress the creation of this item. The fix should be modified to never add this item under any circumstance, ever.

**Comment by pvlakshm** [comment]
This is being tracked external to this repo, here: https://developercommunity.visualstudio.com/content/problem/145856/vs-adds-service-item-to-csproj.html

**Comment by victor-yarema** [comment]
"Fiona Niu[MSFT]
Jun 28, 2018 at 06:57 AM
Thanks for reporting this problem. After careful evaluation of the problem impact & severity we are closing this problem as low priority. We understand that this might not be an ideal resolution for you, but be assured that we don’t make these decisions lightly. We prioritize problem investigations by impact and severity for a broad set of customers; the impact of this problem is limited relative to other existing problems. We have made significant improvements to the product over the past few months, notably in the areas of performance, reliability & general quality of the product. It is possible that this problem has been addressed in the latest version of Visual Studio. We encourage you to update to latest version of Visual Studio and continue to give us feedback."
@ https://developercommunity.visualstudio.com/content/problem/145856/vs-adds-service-item-to-csproj.html

It is not being tracked. It is simply closed with no fix. I don't understand what is the purpose of such an action? To make sure people will not find opened bug and report a new one? Why don't just leave it open with lowest priority?
@pvlakshm , How about reopening it at least here so people will at least know that it was not fixed?
