### ISSUE TITLE
Add support for dotnet test --collect:"Code Coverage" for non VS-Enterprise users

### ISSUE THREAD

**Issue by suryagh** [Microsoft/vstest#1312]
## Description
Can we have code coverage for non-enterprise Visual Studio Users?

`dotnet test --collect:"Code Coverage"` only works if Visual Studio Enterprise is installed.

Ability to check code coverage is important for any application development. So, can we please have this prioritized?

Thanks!

**Comment by AdrienneCohea** [comment]
I'm trying to make the argument at my company to migrate to .NET Core. I can't in good conscience make this argument though because we would be losing code coverage in our CI/CD pipeline.

In my opinion, the enhancement label should be removed for this issue. Code coverage is an integral part of tooling. It is not an enhancement. Build tooling is not feature-complete without code coverage.

**Comment by pvlakshm** [comment]
We are starting on enabling code coverage via `dotnet test` as described in this [RFC](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0021-CodeCoverageForNetCore.md).

**Comment by smadala** [comment]
Dupe of https://github.com/Microsoft/vstest/issues/981 . Installing VS 15.8(non-enterprise also) should fix this issue.
