### ISSUE TITLE
Trx file format

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vstest#1541]
Dear,

I took a look on previouslly reported issues and I found some of them that can relate to this. However, the response in those is inconclusive.

Many tools do relay on the trx file. In case of the test run with MsTest the resulting trx is different then if run with VsTest with trx logger.
Differences between the two TRX outputs are small but are preventing tools such as SpecFlow report generator to correctly process trx file.

The notable differences are:

- //TestRun/TestDefinitions/UnitTest/TestMethod/@ClassName renders not the fully qualified name, but just the namespace.

- The TestDescriptionAttribute is not rendered, but should be in //TestRun/TestDefinitions/UnitTest/Description.

- TestPropertyAttributes are not rendered, but should be in //TestRun/TestDefinitions/UnitTest/Properties.

Is this by design or is it fixed somewhere? How so that the two outputs are different? Any workarounds?

Thanks

**Comment by nigurr** [comment]
@mmajcica Can you please share the trx in both scenarios and highlight the differences?

**Comment by singhsarab** [comment]
@mmajcica 
mstest.exe is on its to deprecation and we do not recommend it.
vstest.console.exe is the recommended runner moving forward. The changes that you see are by design. Example, the description and test property attributes are specific to mstest framework but trx logger is supposed to a generic logger, hence the behavior you see is by design.
