### ISSUE TITLE
dotnet core test support for the Visual Studio Test task

### ISSUE THREAD

**Issue by matthew-horrocks** [Microsoft/vstest#1566]
I've seen various comments, reports and suggestions that dotnet core test support for the Visual Studio Test task is on your backlog and will be addressed.

Is there a timeline for this work? Is it in progress? Is there a beta version of the task we can trial this with?

Thanks,
Matt

**Comment by mayankbansal018** [comment]
@pvlakshm , I suppose we have a story planned for this, can you please share the plan here

**Comment by matthew-horrocks** [comment]
I did wonder this morning if this would have been better asked at https://github.com/Microsoft/vsts-tasks/issues as it relates more to the VSTS Visual Studio Test task.

**Comment by smadala** [comment]
@PBoraMSFT Can you share plan for this?

**Comment by PBoraMSFT** [comment]
@matthew-horrocks - this question is best suited for the vsts-tasks repo as it relates to the task, not the platform. However, I will answer it here since we have it going on. 
dotnet core support in VSTest means different things for different people - it may mean one or more of the following:

1. running dot net core tests using the assembly input 
2. Collecting code coverage using the 'Enable code coverage' - which is currently not supported (as code coverage doesn't support portable pdbs today, but can be worked around using full pdbs) 
3. Running tests by associating them with a test plan/test suite - which is currently not supported. 

#1 works today with the the target framework specified in the console options. 
We are currently working on #2 and expect it to become available in a couple of sprints. 
#3 is in the works, but we have hit some roadblocks, so don't have an ETA to share at this time.

Hope this helps.
