### ISSUE TITLE
Failed to create/publish coverage File.

### ISSUE THREAD

**Issue by Eldadc** [Microsoft/vstest#1650]
## Description
Running vstest command via TFS vnext task with EnableCodeCoverage parameter will create a corrupted coverage file , i.e. 1K, corrupted file.
Can not open it with VS 2017.

## Steps to reproduce
Visual Studio Test task - vstest task on TFS

## Expected behavior
Publish cover results in my build info.

## Actual behavior
1K file  , corrupted file.

## Environment
When exactly same CLI command wad done from a cmd command session on the Agent machine , the command creates coverage file.
When running using CodeCoverage.exe, I got cover results  successfully, The issue is that I can not publish results in my TFS build info.

Thanks,

**Comment by kaadhina** [comment]
Hi,
1. Are you on TFS On-Prem or VSTS? If On-Prem, which version?
2. Can you please enable debug logs in your definition by setting system.debug variable to true and send us the logs? You may choose to mail them to devops_tools@microsoft.com as well.

**Comment by Eldadc** [comment]
Hi,

Thanks for the response.
1. TFS 2018 RC1 on-Prem
2. I enabled , Can you please instruct me what entries should I check , I have organization restriction in order to send my logs
3. I have in my logs the following error :" unable to publish telemetry due to lower agent version"
4. Note : No issues publishing the UT results.

Thanks In Advanced,


Thanks In Advanced,

**Comment by kaadhina** [comment]
1. You ran the vstest.console.exe CLI from the same build agent machine where the task generated a corrupted file, and it generates a valid file. Can you please confirm it fails only via vstest task in tfs and not from CLI on the same machine
2. What was the VS version (You can find the exact version from Help->About in VS)
3. Since we cannot repro this at our end, we will need task logs, vstest diag logs, and the .coverage files for analysis. You can send them over by email to us, if you are not comfortable attaching them here in public forum.
4. Do you see the code coverage report in the build summary page
5. "unable to publish telemetry due to lower agent version" I believe is a warning. You can get past this by using a newer build agent, and it is not related to the code coverage issue you are seeing.

**Comment by Eldadc** [comment]
Thanks on the detailed response.

1. No issues when running via CLI on Agent machine.
2.  VS 15.0.27617.1
3.  unfortunately we have restricted procedure , I can cut part of the log in some parts if that can help.
4.  No cover report , It seems in the log the coverage file have been created but as 1KB size only.

Thanks

**Comment by kaadhina** [comment]
Unfortunately, since we don't have an idea as to what is causing your issue, we will not be able to debug without the logs. You may choose to get in touch with us via the customer support team at https://visualstudio.microsoft.com/team-services/tfs-support/ and they will guide you further in the process.
