### ISSUE TITLE
Improve the cli experience for dotnet test

### ISSUE THREAD

**Issue by singhsarab** [microsoft/vstest#1824]
## Description
> There has been a lot of feedback around the cli experience for dotnet test, here are a few suggestions that can be considered.

o	Show the results using unicode ✔ and ❌ with colors
o	Progress bar (only prints a dot every ~3 seconds just so the user knows we haven’t frozen.) 
o	Clean summary table at the end of run for the whole solution file. Includes Pass/Fail Unicode character, Test Name, and duration.
o	Option to output an html file.

**Comment by jimmylewis** [comment]
Copying some feedback from a VS Feedback ticket:

After running tests in the console, it used to be really easy to search for “Passed”, “Skipped”, and “Failed” tests using those strings. When I used to get a result like:

>Test Run Failed.
Total tests: 6543
Passed: 6502
Failed: 1
Skipped: 40
Total time: 4.7696 Minutes

I could find the failing test just by searching in the console for "Failed".

Now the output uses ✔, !, and X instead of these. X is much more commonly found in test names or output messages (e.g. in “exception” messages or test names containing words like syntax, index. matrix - all of which are in my test bed), so searching becomes less effective to find the test failure.

Worth noting, I couldn't search for ❌ in the VS dev cmd prompt.  I had to use the letter X, which did find the match in the console contents.

**Comment by jpribele** [comment]
Unicode Pass/Fail is bad for farms or other processes are that are capturing tty. 
` û TestName` example output

**Comment by nohwnd** [comment]
(in reaction to PR #2333)

Personally I find the default indicators really nice to look at, but a pain to read and search for in log. I like the change but I don't think adding yet another set of options is the best way to do this. 

Maybe we could consider changing them:
- to something that is a normal character / character group, but is unlikely to turn up in log otherwise. (e.g. use `[-], [+], [!]`, but not just +,-,! or X).  
- put the indicators to the header, like Running tests (Passed √, Failed X, Skipped !). 
- use Passed, Failed, Skipped instead of cryptic signs

~Another problem is that the characters easily get mangled in output, but maybe that is just our problem, because we are likely the only ones running vstest in vstest (in our acceptance tests).~ I see the same issue mentioned above, so there not using unicode would be an advantage as well.

**Comment by jpribele** [comment]
I could live with both unicode and plain text. [Passed √] TestName 
In log file that 2000 tests being able search quickly and reliably is nice. Ctrl+F "[Failed" or "[Passed

**Comment by nohwnd** [comment]
For what it's worth searching for <code>&nbsp;&nbsp;&nbsp;&nbsp;X&nbsp;</code> (four spaces X and one space), will find failed tests pretty consistently, especially if you switch to the raw log view.

(Also passed tests are showing `ï¿½ PassingTest2 [7ms]` in the raw view)

**Comment by singhsarab** [comment]
@nohwnd This was based on the feedback shared by @kendrahavens. Please get this reviewed from her. Thanks.

**Comment by kendrahavens** [comment]
I like @nohwnd 's suggestion of using `[-], [+], [!]`. Overall, the goal was to make it easier to distinguish between the test states at a glance. Icons with color tend to provide faster recognition than the spelled out 'Passed' and 'Failed' states. But since the unicode creates issues for searching I'd agree we can change to a more easily searchable character group.

@jpribele Would the character group `[-], [+], [!]` also be satisfactory?

**Comment by nohwnd** [comment]
I made a quick [poll on twitter](https://twitter.com/nohwnd/status/1235822638066356224?s=20) to involve more people into this.

**Comment by jpribele** [comment]
Plus Minus is fine.

**Comment by duaneking** [comment]
Just want to point out in as respectfully a tone as I can use while at the same time wanting to drive home the importance of this, that  using emoji of ANY KIND violates accessibility standards and is not accessible for the many visually disabled or older software developers who are still very much a part of the software development community.

Please don't use emoji for ANYTHING by default as it can crash text to speech systems used by the disabled and is generally not as accessible anyway.

Allow it via an optional flag maybe, but you should be as inclusive as possible and keep to things like the ADA, etc so it remains legal.

**Comment by nohwnd** [comment]
@duaneking Thank you for your concern 🙂 We will not change the current approach to emojis, in fact it will change back to the Passed, Failed etc. text. 

I am not sure if you took part of the poll above but the majority of voters voted for the text to return, and I think it is the best option as well: 

![image](https://user-images.githubusercontent.com/5735905/79743745-68876400-8305-11ea-8b84-b6cd5c5c55b4.png)

**Comment by duaneking** [comment]
I'm not able to see or reply to this due to errors in the oauth provider used by github, it wont let me log in.  Please reopen.

Thanks, - Duane King

**Comment by nohwnd** [comment]
@duaneking Ithink all the above points were addressed. I just did the last remaining part which is reverting the indicators back to words. That is why this is closed.

**Comment by duaneking** [comment]
Thank you, right now my only ability to answer any of these is through email by responding there because I’m not able to login and view the actual page because of some stupid errors on the github side.Really frustrated by this because it feels like I have been intentionally locked out from commenting on these accessibility issues.

**Comment by nohwnd** [comment]
I am sorry to hear that. Does it happen only on this repo?

**Comment by duaneking** [comment]
Only repro’s owned by Microsoft, as I can otherwise login to github and use it fine and that is why I feel like this is intentional.If Microsoft owns the repo that I have filed a bug on, I cannot see the bug and I cannot reply to it, as every attempt to do so redirects me to an Oauth provider that then locks me out with an error message that sometimes contains a stack trace saying the credentials are not found. Other times it just kicks me out entirely and asks me to login to an internal v- Microsoft account I don’t have access to as I have left ms research.

**Comment by nohwnd** [comment]
Reported your problem.

**Comment by jeffwilcox** [comment]
@duaneking: SSO is a pain for sure when changes happen. Can you confirm for me, whether you are still a vendor, and continuing to work, or that you have fully left, and are looking to continue having access?

We have systems that will eventually remove your account from the orgs and fix this issue automatically, but I can help get this fixed sooner.

If you would like to discuss in private, you can email opensource at microsoft.com and we can go into the specifics?

**Comment by duaneking** [comment]
It seems to be fixed.  Thank you for your offers of assistance.

**Comment by duaneking** [comment]
To be clear: My goal here is no Unicode or anything that would confuse a voice encoder or a standard super cheap braille terminal (under a grand) in the output as blind accessibility requires this stay ASCII text.  I requested this be reopened partly out of worry as I was not able to see the contents of the bug, so please ignore that request.

**Comment by nohwnd** [comment]
At the moment the output contains just letters, basic punctuation characters and parentheses. Success or failure are indicated by the words Failed, Passed, and Skipped.

**Comment by jpribele** [comment]
When will this make its way into Visual Studio ?

**Comment by nohwnd** [comment]
in 16.8.0 release. hopefully preview1, I can't say the exact date though.
