### ISSUE TITLE
Environment variable not found

### ISSUE THREAD

**Issue by bdebaere** [Microsoft/vstest#1831]
## Description
In an ASP .NET Core project it's possible to set environment variables. These variables are not available during local tests however. I've also tried with setting the environment variables in the test project or any other project related to the solution. Of course I could set it globally in Windows but that seems a tad too much. Is there another way to accomplish what I'm trying?

EDIT: small sidenote that these tests should also keep functioning online in Azure Devops where I simply set the environment variable in the pipeline, meaning that any solution should keep the value specified in Azure Devops as the final value.

## Steps to reproduce
Set an environment variable in your projects.
![image](https://user-images.githubusercontent.com/1436449/48134423-2ba6e900-e29a-11e8-9002-adf022a9aa98.png)

## Expected behavior
The environment variable is found. To me at the very least it should be found when specified in the test project.

## Actual behavior
![image](https://user-images.githubusercontent.com/1436449/48134613-bb4c9780-e29a-11e8-99a2-5b482baf12a4.png)
Notice how it's not found when running local tests.

**Comment by karanjitsingh** [comment]
Hi @bdebaere, environment variables won't work since visual studio doesn't pass them down to vstest.console.exe. To achieve this you could use a test run parameter,

Set test run parameters in your runsettings as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <TestRunParameters>
    <Parameter name="env" value="Debug" />
  </TestRunParameters>
</RunSettings>
```

You can access these test run properties in your test project with the `TestContext` object 

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        public TestContext TestContext { get; set; }

        private static TestContext _testContext;

        [ClassInitialize]
        public static void SetupTests(TestContext testContext)
        {
            _testContext = testContext;
        }

        [TestMethod]
        public void TestMethod1()
        {

            var value = TestContext.Properties["env"]; ;
            
        }
    }
}
```

Use the `Override test run parameters` in the vstest task to override these properties

![image](https://user-images.githubusercontent.com/4632805/48180954-a7ad3980-e34b-11e8-9743-6f4ecf6a24a3.png)

Where `$(Environment)` is a pipeline variable.
