### ISSUE TITLE
Unify the behavior of testhost in Full Framework and netcoreapp2.x for multi-target projects that handle GetEntryAssemply()

### ISSUE THREAD

**Issue by moh-hassan** [Microsoft/vstest#1834]
This issue is a continuation to an issue I provided in [NUnit project](https://github.com/nunit/nunit/issues/3084)

The behaviour of testhost is different in multi-target project (net45, netcoreapp2.1) due to the usage Relection.GetEntryAssemply

I investigated the problem in co-operation of @mikkelbu and I reached to the following conclusion:

Testhost (from within NUnit framework) in netcoreapp2.0 Assembly.GetEntryAssembly() returns the assembly hosting testhost.dll, but in net4x it returns null.

The AssemplyCopyrigtAttribute and AssemplyCompanyAttribute are used by CommandLine package

I inspect the testhost.dll which is located in:

                %UserProfile%.packages\microsoft.testplatform.testhost\15.9.0

by right clicking the file -> property\details, I found:

          Copyright is null

I inspected the testhost.dll by dotPeek (.NET Decompiler and Assembly Browser) and found that:

             company Attribute is null

The null values of these assemplyAttributes cause unit test to fail in certain packages  that consider them mandatory (not null).

**Suggested solution:**

- Fill the properties of  AssemplyCopyrigtAttribute and AssemplyCompanyAttribute in testhost.dll to avoid exceptions in the  packages that depend on using GetEntryAssemply as a source for mandatory assemplyAttributes.

- Unify the behaviour of GetEntryAssemply() in testhost for both full FrameWork and netcoreapp2.x 
- If there's no technical reason for GetEntryAssemply to point to testhost, it's nice if VsTest can provide API for hooking GetEntryAssemply() , so users can use like a Mock to point other dll as the entryAssemply.

**Comment by singhsarab** [comment]
@moh-hassan 
1) Copyright and company name attributes, that has already been fixed in the latest packages.

2) I dont understand what GetEntryAssembly behaviour are we talking about here? Do you mean GetCurrentProcessLocation ?

3) Why do you think GetEntryAssembly should not point to testhost, specially in case of net core ? I am just trying understand the use case here.

**Comment by singhsarab** [comment]
@moh-hassan 
Sorry for the delay in response. Thanks for confirming that first part of issue is resolved.

Regarding Assembly.GetEntryAssembly

This is what you reported earlier
`
Testhost (from within NUnit framework) in netcoreapp2.0 Assembly.GetEntryAssembly() returns the assembly hosting testhost.dll, but in net4x it returns null.
`
Reason: 
In case of Dotnet core, there is not concept of appdomains, things are pretty straight forward. Since testhost.dll is the first executing assembly inside dotnet.exe it automatically ensures GetEntryAssembly is set to testhost.dll

In case of FFW however, there is a new appdomain that is created by the test framework adapter to run the tests.
The only way adapter can make testhost the EntryAssembly for this new appdomain is my calling ExecuteAssembly(<testhost>) which does not make sense.
Refer to https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getentryassembly?view=netframework-4.7.2

Hence, this is by-design.

Now in an attempt to unblock your scenario, found a workaround that might interest you.
https://dejanstojanovic.net/aspnet/2015/january/set-entry-assembly-in-unit-testing-methods/

**Comment by moh-hassan** [comment]
@singhsarab , The link of [set_entry_asemply](https://dejanstojanovic.net/aspnet/2015/january/set-entry-assembly-in-unit-testing-methods/) you provide may help in unifying test suit in net4x to be like netcore.
For completion of the solution I want to modify the line:

                  Assembly assembly = Assembly.GetCallingAssembly();
To be:

                 Assembly assembly = {what_is_the_Assembly_of_testhost} .GetCallingAssembly();

Kindly, Can I know what is the assembly  of the  testhost (that Microsoft.NET.Test.Sdk run ) from vsTest API.
