### ISSUE TITLE
VsTest Platform 16.0.0 fails due to Unit Test Adapter exception

### ISSUE THREAD

**Issue by NDDeveloper13** [Microsoft/vstest#1852]
Test Agent is VM with Win7
TFS 2018 - Version 16.131.28106.2
Test assemblies compiled with VS 2017

We use a release definition that is scheduled nightly to run our test regression suite. The tasks that run the automated tests have 2 tasks in the agent phase:
1. VsTest Platform Installer - set to install the latest Pre-Release of the VS Test Platform Installer. 
2. Visual Studio Test - set to run tests in a test plan/test suite for a given test configuration

This morning around 4:12AM CST, all tests started failing due to the following error:
Unit Test Adapter threw exception: 
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

There is no stack trace available:
![image](https://user-images.githubusercontent.com/43071948/49164489-d5efba80-f2f4-11e8-8433-b1768ce95738.png)

Looks like 16.0.0 was released around that time, in the middle of our test regression, so the tasks started installing the new version of the VS Test Platform, and all remaining tests failed with this error.

Here are the VsTest Platform Installer logs:
[VsTestPlatformInstaller11282018.txt](https://github.com/Microsoft/vstest/files/2625600/VsTestPlatformInstaller11282018.txt)

**Comment by prawalagarwal** [comment]
@NDDeveloper13 If you suspect platform is the cause, can you verify this by specifying a version in the Platform Installer task. You can select "Specific Version" and give the exact version: 15.9.1-preview-20181023-04 or 15.9.0

**Comment by NDDeveloper13** [comment]
Yes, I changed the tasks to choose specific version with a version of "15.9.1-preview-20181023-04", and the tests run as expected. It is only when I specify latest version that this happens.

**Comment by acesiddhu** [comment]
@NDDeveloper13 can you confirm if you are running coded ui test? If they are coded ui test 16.0 test platform version wont work because the test dlls are still getting build with 15.* version of coded ui test assemblies where as you are using 16.* version of coded ui test assemblies to run. you need to use 15.* version of vstest tools installer to run your coded ui test till you don't move your build system to build with VS 2019.

**Comment by NDDeveloper13** [comment]
Yes, we are running Coded UI tests.

So, even if I would have chosen Latest Stable version (which I don't have this option in my VS Test Platform Installer task), this issue still would have occurred. I believe there needs to be another option for the overall VS version (15.*, 16.*, etc) so that users can avoid this when you release a new test platform version that requires an upgrade of Visual Studio/TFS.

**Comment by acesiddhu** [comment]
@NDDeveloper13 we suggest to stick to a particular platform version (Unless there is a bug fix or a new feature) for coded ui tests. Given that VS version which you are using is of specific version. More over this problem will occur for only coded ui test because the version of coded ui test assemblies will change with platform version. This issue is not relevant for any other kind of tests.
