### ISSUE TITLE
VsTest doesn't wait fired `DomainUnload` event when unloads test domain

### ISSUE THREAD

**Issue by nvborisenko** [Microsoft/vstest#1873]
Please look at small test project to reproduce issue.
[Domain.zip](https://github.com/Microsoft/vstest/files/2696177/Domain.zip)

Execute tests via `dotnet test` command.

## Expected behavior
`bin\debug\<targetFramework>` folder contains `log.txt` file.

## Actual behavior
`log.txt` file is missing for `netcoreapp2.1` framework.

## Diagnostic logs
Nothing interesting in diag logs.

## Environment
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
MsTest.Framewok 1.4

## Additional info
The issue is not reproducible if create console netcoreapp and execute the same piece of code. Console wait until event handler finishes to execute.

**Comment by nvborisenko** [comment]
I came here from [SpecFlow](https://github.com/techtalk/SpecFlow) repository. To execute a piece of user's code at the end of all tests execution, SpecFlow relies on `DomainUnload` event for all unit frameworks (nunit, xunit, mstest).

@abhishkk can timeout of 100ms be extended? Is it set in vstest or nercore? If this value can be changed somehow, it would be easier way to resolve the issue.

From mstest perspective it's better to use [AssemblyCleanup]/Teardown attributes. So SpecFlow should rely on this attribute instead of DomainUnload event.

**Comment by abhishkk** [comment]
@nvborisenko Timeout of 100 ms is because as soon as all tests ran successfully, we don't expect any background threads or scenario like domain unload event handling.

You can always use Assembly level cleanup/ class level cleanup etc for cleaning up. Similar functionalties are given by all frameworks (mstest, nunit etc). So, we recommend using these cleanup instead of relying on domain unload.

**Comment by nvborisenko** [comment]
Ok, let's forget about SpecFlow and focus on simple example that I provided above. Test subscribed on `DomainUnload` event to test some specific logic inside handler, and handler is not awaited. I think this is confusing situation, given that the behavior is different in `console netcoreapp`, and even given that the behavior is different in `net full framework`.

My opinion is, once it's managed by `vstest`, to fix it somehow on `vstest` side.

**Comment by abhishkk** [comment]
@nvborisenko 
I agree that the behavior is different in console app and test. The change in behavior is intentional.
Reasoning behind this is that expectation from users is to use class/test/assembly level cleanup functionality to cleanup rather than depending on domain unload events or using background threads.

Waiting for all background threads and event handlers to finish even after all tests ran successfully is a reliability concern since tests run within testhost.exe process (and not in user controlled process like console app).

**Comment by abhishkk** [comment]
@nvborisenko Please let us know in case you have any further questions.

**Comment by nvborisenko** [comment]
Thanks for detailed explanation.
