### ISSUE TITLE
Incorrect warnings logged in diagnostics ".host" file for nunit tests

### ISSUE THREAD

**Issue by mikkelbu** [Microsoft/vstest#1894]
The following problem was raised in nunit/nunit3-vs-adapter#587 by @bachowny, so I cannot fill in all the necessary information, but we suspect that the problem is in vstest and not in nunit3-vs-adapter.

## Description
I work on some NUnit tests which we run under dotnetcore via vstest.

I've turned on some logging to investigate an issue with the test suite aborting with no message (that's covered elsewhere so I won't go into details here).

So we run the tests like so:

`dotnet vstest MontrealTests.dll /Logger:"trx;LogFileName=RESULTS.trx" /Diag:"TestResults/Diagnostics.txt;TraceLevel=Warning"`

What I'm noticing though is that we also get a file created called e.g. Diagnostics.host.19-01-18_12-46-24_25406_5.txt. I believe this file is created by NUnit's adapter which is why I'm posting here.

Inside this file, for every single test in my combinatorial tests (which is quite a lot of them), I get a message like this:

`TpTrace Warning: 0 : 15036, 30, 2019/01/18, 12:53:45.800, 839984326897, testhost.dll, TestRunCache: No test found corresponding to testResult 'PlaceOrderAndCancel(Bid,XMOD:CGBZ18CGBH19:x-1) Passed' in inProgress list.`
`TpTrace Warning: 0 : 15036, 30, 2019/01/18, 12:53:46.462, 839986519777, testhost.dll, InProgressTests is null`

To be clear, there is nothing wrong with the tests or the results file that is generated. Those are working and the intermittent failure I'm investigating is a separate issue.

This spammy warning though is quite annoying and means that I get several megabytes of diagnostic logs even when nothing has gone wrong.

It would be great if I could suppress this warning or if we just stopped logging it when it's clearly incorrect.

Thanks in advance for any assistance!

## Steps to reproduce
For the commandline see above, regarding the sample project, framework etc. perhaps @bachowny can supply this.

## Expected behavior
That no warnings appear - or that it is possible to disable these warnings.

## Actual behavior
A lot of warnings about `No test found corresponding to testResult '.......' in inProgress list` and `InProgressTests is null`.

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

I don't know, but perhaps @bachowny can supply this.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

I don't know, but perhaps @bachowny can supply this.

**Comment by mayankbansal018** [comment]
@mikkelbu 
> What I'm noticing though is that we also get a file created called e.g. Diagnostics.host.19-01-18_12-46-24_25406_5.txt. I believe this file is created by NUnit's adapter which is why I'm posting here.

The file is created by test platform only. See the name host appended to it, it signifies that these logs are related to testhost process, where the adapter is actually loaded, & tests are run.

The diagnostics file is generally used by us, to diagnose any errors when test session ends abruptly. However since you are using it in this fashion, & you wish to reduce the messages, I would suggest that you use /Diag:"TestResults/Diagnostics.txt;TraceLevel=**Error**" instead of /Diag:"TestResults/Diagnostics.txt;TraceLevel=**Warning**", that would significantly reduce what messages are printed in the file

**Comment by bachowny** [comment]
> The diagnostics file is generally used by us, to diagnose any errors when test session ends abruptly. However since you are using it in this fashion, & you wish to reduce the messages, I would suggest that you use /Diag:"TestResults/Diagnostics.txt;TraceLevel=**Error**" instead of /Diag:"TestResults/Diagnostics.txt;TraceLevel=**Warning**", that would significantly reduce what messages are printed in the file

It may be by design to show warning messages when the logging level is set to warning, but warning that a test isn't found and that there's no tests in progress, when the tests ARE in progress and the test JUST RAN without failure, seems highly illogical.

**Comment by mayankbansal018** [comment]
@bachowny I agree that those logs might not make sense, but they do happen especially when we mark a Test as being active, & return the result of tests that have been executed. 

Also since these are plain diagnostics logs, required to identify abnormal failures, we would have not added any extra logic to recheck while logging. The logging point simply records data if it finds something missing.

>Just to supply some of the missing information, this occurs when using vstest 15.5.0 via dotnet 2.1.4 for both Windows Server 2012 and CentOS 7.

The option to pass TraceLevel in CLI is not available in that version, if you wish to minimize the logs, please use the latest version.

**Comment by bachowny** [comment]
I guess this is more of an annoyance than anything else but for posterity I'll just restate what you've said: This warning about tests not existing is logged **because we don't expect tests to be executed when we are executing tests**.

If that truly is "by design", then there's not much I can expect in the way of improvement! :-)

Also the TraceLevel switch does work as expected with those versions so I'm not sure what the story is. It may be that the AWS instances we're using to run the tests are upgraded compared to the local test machines I queried to get versions.
