### ISSUE TITLE
Is it possible to run netcoreapp2.1 mstest tests on an Azure DevOps Release agent without using dotnet publish?

### ISSUE THREAD

**Issue by wouterroos** [Microsoft/vstest#1928]
Hi,

See title, we would like to run our `netcoreapp2.1` test assemblies in the same way as we do for `net461` but are running into the following error: 

`Unable to find d:\a\r1\a\Project\e2e\bin\Release\netcoreapp2.1\testhost.dll. Please publish your test project and retry.`

Targetting the exact same assemblies compiled for `net461` runs without any issue, so is there any way to get this to work with just the build output, so without having to use `dotnet publish` for all our integration test assemblies? 

Also see this link explaining a similar issue: https://stackoverflow.com/questions/54729313/vsts-task-error-when-run-integration-tests-in-net-core-2-1

Thanks in advance,

Best regards,

Wouter

**Comment by jayaranigarg** [comment]
@wouterroos : In case of net461, all dependencies of your test project gets copied to your build output folder and hence things work fine. But in case of dotnet core, not all dependencies are copied to your build output folder and it depends on *.deps.json to figure out various dependencies.

So, you will have to use a `dotnet publish` so that all dependencies(from build ouput and other locations) are indeed copied to the test location and tests work fine.

**Comment by jayaranigarg** [comment]
Closing the issue from our end. Let us know if you need further assistance on this!

**Comment by wouterroos** [comment]
Thanks for your help.
