### ISSUE TITLE
Unable to read beyond the end of the stream in Linux CI

### ISSUE THREAD

**Issue by PierreLSE** [Microsoft/vstest#1932]
## Description
Hello, I have a test that pass on windows on my local computer and azure devops and on my local computer on ubuntu 1604 but the test always crashes with a Hosted Ubuntu 1604 in Devops

## Steps to reproduce
Cannot share the repo to reproduce the issue

Here is the command 
`[command]/opt/hostedtoolcache/dncs/2.1.504/x64/dotnet vstest /home/vsts/work/r1/a/cnm-ComponentTests/Component-Tests-x64/IoTHubAgent.ComponentTests.dll --Settings:/home/vsts/work/r1/a/cnm-ComponentTests/Component-Tests-x64/testParameters.runsettings --logger:console;verbosity=debug --Tests:IHA_Certificate_based_Bootstrap_TC1_Nominal --InIsolation --Diag:IHA_Certificate_based_Bootstrap_TC1_Nominal.log;tracelevel=verbose --Blame`

## Expected behavior
The test pass
`TestHostManagerCallbacks.ExitCallBack: Testhost processId: 3986 exited with exitcode: 0 error: `

`dotnet vstest IHATests/IoTHubAgent.ComponentTests.dll --Settings:IHATests/testParameters_dmnpint.runsettings --logger:"trx;LogFileName=CBBootstrapTests.trx"  --Tests:IHA_Certificate_based_Bootstrap_TC1_Nominal --Diag:CBB_TC1.log
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test discovery, please wait...
Logging Vstest Diagnostics in file: /home/code/IoTHubAgentComponentTests/scripts/CBB_TC1.log
gedit WARNING: Overwriting results file: /home/code/IoTHubAgentComponentTests/scripts/TestResults/CBBootstrapTests.trx
Results File: /home/code/IoTHubAgentComponentTests/scripts/TestResults/CBBootstrapTests.trx
Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.`

## Actual behavior
VsTest return an error but doesn't say where the test crashes

`TpTrace Error: 0 : 4919, 8, 2019/02/28, 11:21:39.387, 1019946907899, vstest.console.dll, Socket: Message loop: failed to receive message due to socket error System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.BinaryReader.ReadByte()
at System.IO.BinaryReader.Read7BitEncodedInt()
at System.IO.BinaryReader.ReadString()
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action 1 errorHandler, CancellationToken cancellationToken), remoteEndPoint: 127.0.0.1:41583 localEndPoint: 127.0.0.1:42527
TpTrace Information: 0 : 4919, 8, 2019/02/28, 11:21:39.388, 1019948081097, vstest.console.dll, SocketServer.PrivateStop: Stopp server endPoint: error: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.`

## Diagnostic logs
Log of devops CI
[diag.log](https://github.com/Microsoft/vstest/files/2915604/diag.log)

## Environment
Ubuntu 1604, dotnet sdk 2.1.504

**Comment by mayankbansal018** [comment]
@PierreLSE it looks similar to https://github.com/Microsoft/vstest/issues/1069 can you please verify.

**Comment by PierreLSE** [comment]
@mayankbansal018 Yes, but there is no solution in this one. I tried --Blame:CollectDump;CollectAlways=true;DumpType=full but it is not supported on Linux.

**Comment by cmbankester** [comment]
I've been seeing this issue as well, when running tests in the microsoft/dotnet:2.2.104-sdk-alpine Docker container. The tests run fine on Windows, but in the container they seem to fail after some number of passes (which run-to-run). Also, on Linux I can run the tests one-by-one and they pass fine. Diagnostic logs indicate the test host crashes, which leads to the "Unable to read beyond the end of the stream" issue. I can provide some diagnostic logs if need be, but I'll need to sanitize some sensitive test names in order to do so.

**Comment by jayaranigarg** [comment]
@PierreLSE : Blame datacollector works in Devops CI workflow.
To enable blame, make sure following things are enabled in your VSTest Task:
1. Under Execution options: Check `Collect advanced diagnostics in case of catastrophic failures`
2. Under Execution options: Test PLatform version should be greater than 15.9 ( i.e. either choose `latest` or choose `Installed by Tools Installer`
3. Under Advanced execution options, Batch options - choose `Specify a batch size`
(Note- No need to give --blame switch in CI workflow)

Blame datacollector will help understand if the testhost is crashing due to some test defect and which particular test is causing the crash.

Also, have a variable in your build definition i.e. `system.debug=true`. This will produce 3 output files in your attachment logs: log*.txt, log.host*.txt, log.datacollector*.txt
Please share the attachment logs with us.

**Comment by jayaranigarg** [comment]
@cmbankester : Please share the logs requested in previous comment.

**Comment by PierreLSE** [comment]
@jayaranigarg 
Those options doesn't work in VsTest Run with a Hosted Ubuntu 1604 i get this error : 
This task is supported only on Windows agents and cannot be used on other platforms

To test on linux, i use a .NET Core task and specify a custom command

**Comment by cmbankester** [comment]
After further testing, I believe the issue with my test suite was ultimately caused by [this EFCore/SQLite issue](https://github.com/aspnet/EntityFrameworkCore/issues/14504). In the latest version of the Dotnet SDK Alpine Linux Docker container, there is apparently an issue with using EF Core + SQLite where the SQLite process seg faults and does not send any stderr when it does so. And since the Dotnet test host captures the output from the process to display when an error occurs (see: [ProcessHelper#LaunchProcess](https://github.com/Microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs#L46)), the displayed error is empty.

I still believe that the error-handling/displaying logic in the vstest test host manager should be more robust, so as to make these host-process-crashes easier to diagnose, but at this point it does not appear that the cause of my particular issue resides in this codebase.

**Comment by PierreLSE** [comment]
So anybody has an idea on how to get a dump in the linux CI ?

**Comment by ShreyasRmsft** [comment]
@cmbankester do you have any suggestion on how we could detect this and chain forward information from the testhost?

<br>

> So anybody has an idea on how to get a dump in the linux CI ?


As for this we are looking for a solution...

**Comment by cltshivash** [comment]
https://www.raydbg.com/2018/Debugging-Net-Core-on-Linux-with-LLDB/
http://blogs.microsoft.co.il/sasha/2017/02/26/analyzing-a-net-core-core-dump-on-linux/

Couple of links to help with dump creation on linux machines
