### ISSUE TITLE
Version 16.0.0 has breaking change for Framework:FrameCore10 & NetCoreApp2.0 support

### ISSUE THREAD

**Issue by chrish619** [Microsoft/vstest#1933]
## Steps to reproduce
* Set up an Azure DevOps Build pipeline
* Use Test Platform installer Build step & Visual Studio Test step (using tools installed by previous step)
* Author UnitTests to target NetCoreApp2.0
* Explicitly set /Framework:FrameworkCore10 (This is the only documented Framework switch available for .Net Core)

## Expected behavior
Run tests built against Netstandard/NetCoreApp2.0, via the vstest.console (so I can obtain Test Results / coverage)

## Actual behavior
Test runner throws error "The given test sources target multiple frameworks/platforms that are incompatible. Please make sure the sources target the same framework and platform."

## Version 16.0.0-preview-20190203-03
```
[command]D:\agent\_work\_tool\VsTest\16.0.0-preview-20190203-03\ia32\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe @D:\agent\_work\_temp\fa63cf41-3b48-11e9-aacf-17058a5b4157.txt
Microsoft (R) Test Execution Command Line Tool Version 16.0.0-preview-20190203-03
Copyright (c) Microsoft Corporation.  All rights reserved.

vstest.console.exe 
"D:\agent\_work\2\s\{project}\bin\Release\netcoreapp2.0\{project}.dll"
/Settings:"D:\agent\_work\_temp\08ed4690-3b49-11e9-aacf-17058a5b4157.runsettings"
/logger:"trx"
/TestAdapterPath:"D:\agent\_work\2\s"
/Framework:FrameworkCore10
Starting test execution, please wait...
Test run will use DLL(s) built for framework .NETCoreApp,Version=v1.0 and platform X86. Following DLL(s) do not match framework/platform settings.
{project}.dll is built for Framework 2.0 and Platform AnyCPU.
```

## Version 16.0.0
```
[command]D:\agent\_work\_tool\VsTest\16.0.0\ia32\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe @D:\agent\_work\_temp\af6db1d1-3bb2-11e9-aadf-3d3f782c9a91.txt
Microsoft (R) Test Execution Command Line Tool Version 16.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

vstest.console.exe 
"D:\agent\_work\2\s\{project}\bin\Release\netcoreapp2.0\{project}.dll"
/Settings:"D:\agent\_work\_temp\bbe2c810-3bb2-11e9-aadf-3d3f782c9a91.runsettings"
/logger:"trx"
/TestAdapterPath:"D:\agent\_work\2\s"
/Framework:FrameworkCore10
Starting test execution, please wait...

The given test sources target multiple frameworks/platforms that are incompatible. Please make sure the sources target the same framework and platform.
##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
##[error]Error: The process 'D:\agent\_work\_tool\VsTest\16.0.0\ia32\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe' failed with exit code 1
##[warning]No results found to publish.
##[error]VsTest task failed.
```

**Comment by vagisha-nidhi** [comment]
@chrish619 
We have changes in 16.0.0 regarding running tests targeting multiple framework dlls and incompatible target framework given by the user which is mentioned in the release notes [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1600).
According to the associated changes, multiple dlls targeting different frameworks (version irrespective) will throw a framework/architecture incompatible error. Explanation : if there is one dll targeting .NETFramework and the other targeting .NETCore or vice-versa, the run would be aborted. Earlier we used to spit out warnings and run tests from one of the dlls (skipping the other dlls).
The scenario where all dlls are of either .NETFramework or .NETCore (even if versions are different) should work seamlessly as before.
The other change we made was that if a dll is .NetCore and user explicitly sets /Framework to .NETFramework or dll is .NETFramework and /Framework is set to .NetCore(i.e. frameworkcore10), this gets aborted due to mismatch between given dlls and user provided input.
![image](https://user-images.githubusercontent.com/13175100/53717098-1ecb8800-3e7d-11e9-8f4c-2a705fe60e09.png)

Your scenario clearly mentions that you are trying to run a dll that is targeting .NetCore2.0 with explicit framework setting to **/Framework:FrameworkCore10**. This should work without any break. I have tried to repro this as well. 
I provided a NetCoreApp 2.0 dll with framework explicitly set to FrameworkCore10 (in the runsettings).

```
vstest.console.exe "C:\Users\vanidhi\source\repos\NetCoreProject10\NetCore20\bin\Debug\netcoreapp2.0\NetCore20.dll"
/Settings:"C:\Users\vanidhi\Desktop\abc.runsettings"
/logger:"trx"
/TestAdapterPath:"C:\Users\vanidhi\source\repos\NetCoreProject10\NetCore20\bin\Debug\netcoreapp2.0"
/diag:"E:\vanidhiagent\_work\_temp\0116d160-3e4c-11e9-9d6b-bb7a70367617.txt"
Starting test execution, please wait...
Logging Vstest Diagnostics in file: E:\vanidhiagent\_work\_temp\0116d160-3e4c-11e9-9d6b-bb7a70367617.txt
The following DLL(s) do not match the specified framework .NETCoreApp,Version=v1.0 and platform X86 settings.

NetCore20.dll is built for Framework 2.0 and Platform AnyCPU.
Ensure that the test assemblies target the specified framework/platform settings. Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
Logging TestHost Diagnostics in file: E:\vanidhiagent\_work\_temp\0116d160-3e4c-11e9-9d6b-bb7a70367617.host.19-03-04_12-36-17_73449_5.txt
Passed   TestMethod1
Results File: C:\Users\vanidhi\Desktop\TestResults\vanidhi_VANIDHI-DESK_2019-03-04_12_36_19_230.trx

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.5352 Seconds
```
Runsettings 
  ```
<RunConfiguration>
    <TargetPlatform>x86</TargetPlatform>

    <!-- Framework35 | [Framework40] | Framework45 -->
    <TargetFrameworkVersion>FrameworkCore10</TargetFrameworkVersion>
  </RunConfiguration>
```
Can you please check if you are providing multiple dlls targeting different frameworks(the 1st scenario I mentioned) which is causing the run abort? It would be easier if you could provide a sample repro project for us to look into.

**Comment by vagisha-nidhi** [comment]
Closing this issue as we have reverted the change. Please refer this [comment ](https://github.com/Microsoft/vstest/issues/1931#issuecomment-469520519)for details.
