### ISSUE TITLE
Do Microsoft.NET.Test.Sdk releases have minimum Visual Studio requirements?

### ISSUE THREAD

**Issue by bording** [Microsoft/vstest#1937]
The version numbers of Microsoft.NET.Test.Sdk seem to correspond to Visual Studio version numbers, but does that actually convey any meaningful information? Do any Microsoft.NET.Test.Sdk  releases have specific minimum Visual Studio requirements?

For example, I see that Microsoft.NET.Test.Sdk 16.0.1 is out. If I update my test projects to use it, can I still use Visual Studio 2017 without issues, or does the 16.x version number mean I need to use it with VS 2019 only?

Is this documented somewhere that I just haven't run across yet?

**Comment by jayaranigarg** [comment]
@bording : Thank you for the feedback. There is no change in the specific Visual Studio requirements. It is same as earlier. Refer this link : https://github.com/Microsoft/vstest-docs/blob/master/docs/contribute.md#prerequisites

If you update your test projects to use the latest nuget packages i.e. 16.0.1, things should work fine in VS2017. Since there were no changes from usage perspective, we have not released any documentation.

You can always checkout any documentation w.r.t requirements here : https://github.com/Microsoft/vstest-docs

**Comment by bording** [comment]
Thanks for the information. Given how the version numbers seem to be tracking the Visual Studio version numbers, I think that can be somewhat confusing, especially given that things like the .NET Core SDK itself does have minimum VS requirements.

> Refer this link : https://github.com/Microsoft/vstest-docs/blob/master/docs/contribute.md#prerequisites

Is that link correct? I don't really see anything related to VS with that. [This link](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0005-Test-Platform-SDK.md#sdk-requirements) seems closer to what I was expecting to see, but it seems like it hasn't been updated for information on 16.x.

As a point of feedback, you might want to consider altering your versioning strategy if you aren't actually trying to indicate that a given version is associated with the same version of Visual Studio.

**Comment by napalm684** [comment]
Related to this post I am using 16.0.1 and VS 2017 is unable to run the tests.  VS sees them but doesn't execute with the progress bar just cycling over and over?

**Comment by cltshivash** [comment]
Using 16.0.1 version of Microsoft.NET.Test.Sdk on VS 2017 works fine.
