### ISSUE TITLE
.NET 3.5 Unit Tests No Longer Work

### ISSUE THREAD

**Issue by jbrown16** [Microsoft/vstest#1945]
## Description
Unit tests for .NET 3.5 projects no longer work in VS 2017 (v15.9.8). A fix for this was proposed and implemented in #1896 but it was only pushed into the VS 2019 release, not for 2017. According to some previous discussion on the issue, .NET 3.5 tests were working during some earlier version in 15.x.x which leads me to believe that this should still be supported. This lack of a fix in the 2017 releases is blocking my development, so I'm hoping that this can get escalated to support VS 2017 releases as well in a timely fashion.

## Steps to reproduce
1. Create a project targeting .NET 3.5 in the latest version of visual studio (15.9.8).
2. Create a unit test.
3. Run the unit test.

## Expected behavior
Tests will run successfully.

## Actual behavior
Tests fail to run and output the following error message:
`Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Framework35 is not supported. For projects targeting .Net Framework 3.5, please use Framework40 to run tests in CLR 4.0 "compatibility mode".`

## Environment
Windows 10 64-bit
Visual Studio 2017 Enterprise v15.9.8

**Comment by singhsarab** [comment]
@jbrown16 I am trying to push it for 15.9.9, will update once it is in. Thanks for your patience.

**Comment by singhsarab** [comment]
I am sorry, it could not make it to 15.9.9, rooting for 15.9.10

**Comment by jbrown16** [comment]
@singhsarab, Do you happen to know the timeframe of the 15.9.9 and 15.9.10 releases? Also, is this due to the lack of necessity for the fix or just the timing of when you can get the change in? Thanks for you help on this.

**Comment by singhsarab** [comment]
15.9.9 should be out soon in a day or two, while expect 15.9.10 to be released early next month.

Since we have already released the packages with the fix. I can try to unblock you.
- You can download the package https://www.nuget.org/packages/Microsoft.TestPlatform/15.9.1
- Unblock the nuget package (RightClick->Properties), and extract the contents
- Take backup of C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform 
- Replace the contents in the above folder by copying the contents from tools\net451\Common7\IDE\Extensions\TestPlatform directory in the nuget package.

**Comment by jbrown16** [comment]
@singhsarab I am pleased to report that my first test run is working successfully! Thank you so much for helping me take care of this. I'll let you know if I have anymore issues and I'll also watch for the 15.9.10 release.

**Comment by singhsarab** [comment]
This is now officially supported in 15.9.10.
Thanks :)

**Comment by jbrown16** [comment]
Awesome! Thank you so much, @singhsarab!
