### ISSUE TITLE
dotnet test seems to ignore runsettings MaxCpuCount

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/vstest#1966]
## Description

`dotnet test` when run against a solution that contains multiple test projects, appears to spin up a parallel test runner for each test project.

Attempting to limit to one test runner at a time via the MaxCpuCount value in a .runsettings file doesn't work.

## Steps to reproduce
1. Create a solution with two or more test projects that use NUnit
2. Create a .runsettings file that sets MaxCpuCount=1
2. run `dotnet test --settings pathtofile.runsettings`

## Expected behavior
Tests assemblies are run sequentially

## Actual behavior
Test assemblies are run in parallel (seen in my case where the tests are database tests and they end up fighting for access to the database)

## Environment

Windows 10 1809, vstest.console 15.0.28307.421
.NET Core SDK 2.2.200/2.2.202

**Comment by ShreyasRmsft** [comment]
@flcdrg vstest receives one dll at a time when you run dotnet test on an sln. 


When you run dotnet test at an sln, after dotnet finishes build it passed the built binaries on to vstest to run the tests. This means that the build is happening in parallel and soon after the tests are starting.

MaxCpuCount will have no impact on this process whatsoever. One way to get your dlls to run in sequence is to make sure build happens in sequence. Otherwise can you open an issue in the dotnet cli repo to requesting for a flag or parameter to ensure tests run in sequence regardless of when build completes.

**Comment by flcdrg** [comment]
And this is still the case if you run `dotnet test --no-build --no-restore` ?

**Comment by OsirisTerje** [comment]
@ShreyasRmsft   It is unfortunate , that dotnet test doesn't use the information in the runsettings file. This file can be added as a parameter for dotnet test, and for the user it would feel natural that when one turns off parallel here, it also works for dotnet itself, and not just for the underlying vstest.

**Comment by ShreyasRmsft** [comment]
@OsirisTerje agreed. The current experience is a little unintuitive.

**Comment by mayankbansal018** [comment]
@flcdrg , @OsirisTerje dotnet test currently works on a single project, i.e. even you pass a solution file to it, internally dotnet test is invoked individually for every UT project. Doing this ensures that test doesn't have to wait till build is complete, & helps in performance. Hence there is no need for it to honor `MaxCpuCount`

However we are working on bringing in support of running `dlls` with dotnet test, the spec is yet to be closed, but the idea is to bring parity with how `dotnet vstest` works. 

Current `dotnet vstest` honor's `MaxCpuCount`, & eventually in cases of dll, `dotnet test` will also start to do so.

**Comment by OsirisTerje** [comment]
Thanks @mayankbansal018 !

**Comment by Mpdreamz** [comment]
Even the fact that console loggers will be intermixed makes me want to run sequentially on CI to get sane output. `MaxCpuCount` is not a fix.

Please reconsider reopening this.

**Comment by papatelst** [comment]
I have **Visual studio 2019 Version 16.5.0 Preview 2.0** and use **.net core version "3.1.100"**
Based on documentation at [link](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?branch=release-16.4&view=vs-2019), I tried using following command to restrict **MaxCpuCount** to 2 threads for my 1 test project called **UITests**, which has 3 tests with **nunit category = foo.**
`vstest.console.exe artifacts\tests\UITests.dll /Settings:UITests\foo.runsettings /TestCaseFilter:"TestCategory=foo"`
Under UITests project, I have following foo.runsettings xml file
`<?xml version="1.0" encoding="utf-8" ?>
<RunSettings>
<RunConfiguration>
  <MaxCpuCount>2</MaxCpuCount>
</RunConfiguration>
</RunSettings>`
However, it opens 3 threads in parallel, instead of 2., which basically means it ignores MaxCpuCount configuration.

I also tried dotnet.exe test command as follows which did not work either and opens 3 threads in parallel.
`dotnet.exe test UITests\UITests.csproj -s UITests\foo.runsettings --filter "TestCategory=foo" --no-build`
Please guide as to what am I doing wrong here. 
Per comments above, it seems that it should atleast work with vstest.console.exe command if not with dotnet.exe test command.
I cannot use Nunit parameters as .net core tests cannot be run with nunit parameters because Nunit console does not work with .net core yet as mentioned at [issue](https://github.com/nunit/nunit-console/issues/475)

**Comment by jefflill** [comment]
FYI: The `NumberOfTestWorkers` trick mentioned by @papatelst described in detail for xunit here:

https://github.com/nforgeio/neonKUBE/issues/1203

**Comment by smchan514** [comment]
For anyone still looking for a solution, there is the command line option `-m:1` which _specifies the maximum number of concurrent processes to use when building_.

```
dotnet test -m:1 MyUnitTests.sln
```

Ref: 
1. https://github.com/dotnet/sdk/issues/10178
2. [MSBuild command-line reference -- Switches](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#switches)

**Comment by aaronasmith** [comment]
> For anyone still looking for a solution, there is the command line option `-m:1` which _specifies the maximum number of concurrent processes to use when building_.
> 
> ```
> dotnet test -m:1 MyUnitTests.sln
> ```
> 
> Ref:
> 
> 1. [Add parameter to ensure tests run in sequence regardless of when build completes dotnet/sdk#10178](https://github.com/dotnet/sdk/issues/10178)
> 2. [MSBuild command-line reference -- Switches](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#switches)

This seems to have been slightly broken in the latest SDK.  The -m:1 switch must come directly after `dotnet test` and before the solution file or it is ignored.
