### ISSUE TITLE
SQL Unit Testing Support?

### ISSUE THREAD

**Issue by AndyL-Edit** [Microsoft/vstest#1984]
We are using an Azure DevOps Release Pipeline to deploy a dacpac to a server which does not have Visual Studio installed. This all works great. We now wish to run some database Unit tests against this database. We have a step in the pipeline that runs the "Visual Studio Test Platform Installer" and gets the latest stable version of vstest.console.exe from Nuget and places it in the Tools folder for the Azure Release Agent on the server. The Visual Studio Test task then attempts to run the test assembly against the test platform installed by the tools installer. The error we then get is:

"Assembly Initialization method Project1UnitTest.SqlDatabaseSetup.InitializeAssembly threw exception. System.TypeInitializationException: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Tools.Schema.Sql.UnitTesting.SqlDatabaseTestClass' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.Data.Tools.Schema.Sql.UnitTesting.SqlDatabaseTestService' threw an exception. ---> System.Runtime.InteropServices.COMException: Element not found. (Exception from HRESULT: 0x80070490). Aborting test execution."

All the dlls are copied to the server in the Articfacts directory, including the Microsoft.Data.Tools.... dlls

It looks like the vstest runner does not support the SQL unit testing dlls We have installed SSDT as well with no joy.

Has anyone else experienced this or indeed managed to get SQL unit tests to run via Azure Pipelines without Visual Studio installed on the target box?

**Comment by mayankbansal018** [comment]
@AndyL-Edit , can you please try this scenario on a clean box with no VS Install? From the error it doesn't look anything specific to platform,& since the exception is thrown in Assembly Initialize, it means platform was able to load the test adapter, which then tried to run the tests. 

However when the initialize was invoked for your test class, some dependencies were not found, which probably get installed when VS is present on box.

**Comment by AndyL-Edit** [comment]
Forgive me - but I am a little confused. This was on a box with no VS install, That is the issue I am trying to overcome and why we are using the "Visual Studio Test Platform Installer" task in devOps?

**Comment by mayankbansal018** [comment]
@AndyL-Edit , the "Test Platform Installer" task is for users who don't have VS installed on their build agents, & would simply want to run tests. This also helps in faster servicing with bugs fixes in test platform, which would otherwise be only available with VS releases.

The task itself brings in all the dependencies for test platform which runs the tests, however the dependencies that the test code itself has to be solved by users themselves, e.g. in your case you might VS present on the box to have all the SQL dependencies, which is why the tests are failing.

Also the "Test Installer task" is not the only way user can run tests, if you have VS on your build agents, you don't need to add the step of "test platform installer" , you can simply chose one of the other option in VS test task
![test task](https://user-images.githubusercontent.com/24792973/55972324-ebacbd80-5ca0-11e9-8290-03cc9111c0ed.PNG)

**Comment by AndyL-Edit** [comment]
Thanks for your assistance.
We have found a workarounf for this issue.

**Comment by danielstefanescu** [comment]
@AndyL-Edit care to share the workaround? Thanks.

**Comment by DopefishJustin** [comment]
This doesn't solve OP's problem as stated, but since the error message is not self-explanatory and this thread is the sole hit on Google for it, I'll mention what worked in my situation. It turns out that due to misunderstanding the docs or copy-pasting from somewhere, I was using the test platform installer in azure-pipelines.yml even though the full Visual Studio was installed on the build agents so there was no need for it. And for whatever reason the SQL unit testing dependency still fails even then. In which case the solution is to just switch to running the tests in VS instead:

```diff
-  - task: VisualStudioTestPlatformInstaller@1
-    inputs:
-      packageFeedSelector: 'nugetOrg'
-      versionSelector: 'latestStable'
-
   - task: VSTest@2
     timeoutInMinutes: 20
     inputs:
       platform: '$(buildPlatform)'
       configuration: '$(buildConfiguration)'
-      vsTestVersion: 'toolsInstaller'
+      vsTestVersion: '16.0'
```
