### ISSUE TITLE
IVstestConsoleWrapper.EndSession leaves console processes hanging around

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#2026]
## Description
Calling into IVsTestConsoleWrapper.EndSession does not automatically dispose vstest.console processes and a StartSession thereafter creates a new process. This is in context of tying in diagnostic logging of vstest.console to an IDE switch so its easier to collect logs.

## Expected behavior
vstest.console processes need to be cleaned up/recycled.

## Actual behavior
Multiple vstest.console processes lying around.

## Environment
I'm trying this on the latest previews of VS 2019 update 2.

**Comment by singhsarab** [comment]
@ShreyasRmsft Seems to be similar to what we were talking about the other day. Do you have an issue filed already ?

**Comment by ShreyasRmsft** [comment]
@singhsarab there is an internal bug on mseng. Haven't filed an issue on the repo.

**Comment by vagisha-nidhi** [comment]
@AbhitejJohn Looked at the issue here. The end session sends a session end message and and when vstest.console receives it, it gets disposed here [https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Client/DesignMode/DesignModeClient.cs#L218](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Client/DesignMode/DesignModeClient.cs#L218)
There are multiple vstest.console lying around which which is because of this [https://github.com/microsoft/vstest/issues/2034](https://github.com/microsoft/vstest/issues/2034).
I will shortly fix this.

**Comment by AbhitejJohn** [comment]
@vagisha-nidhi : Thanks, can this issue be closed out now?

**Comment by vagisha-nidhi** [comment]
@AbhitejJohn Yes. Closing this.

**Comment by drognanar** [comment]
Reopening this issue as I'm still seeing the vstest.console processes hanging. I'm calling StartSession and EndSession without requesting a discovery and run in between. In this specific case the vstest.console process stays around.

**Comment by drognanar** [comment]
From my quick look at the code it seems that EndSession does not wait for the handshake with the test console to be established. This introduces a race between the handshake and EndSession messages sent to the testhost.
