### ISSUE TITLE
Is it possible to associate custom test with TFS/MTM Test case?

### ISSUE THREAD

**Issue by nramprakash88** [microsoft/vstest#2036]
I have created a VSIX based test adapter using visual studio test platform(vstest) API. It will read my custom test item(in xml) where my test information is there and it will enable the unit test explorer in visual studio to list my tests written in custom test file. (I referred the following blog to create the adapter
https://devblogs.microsoft.com/devops/writing-a-visual-studio-2012-unit-test-adapter/#)

I am able to get my custom tests discovered under Unit Test Explorer. But I am not able to associate those tests with TFS/MTM manual test cases. When I right click the test case, the "Associate to Test Case" option is disabled.

Is it possible to get that option enabled to associate with a manual TFS test case ?

NOTE: I am able to associate a .net based unit test method by this way. My VS version is 15.9.2

**Comment by cltshivash** [comment]
@nramprakash88 Association of test case is supported currently for only NUnit, xUnit and MSTest test adapters in VS to cater to customers who were using this flow earlier. We recommend users to declare the tests to run as part of the pipeline instead of defining a test case, associating it with a test method and then executing it.

@PBoraMSFT : fyi.
