### ISSUE TITLE
Difference between TestPlatform/vstest.console.exe and TestWindow/vstest.console.exe?

### ISSUE THREAD

**Issue by mehagar** [microsoft/vstest#2077]
I see the file sizes and versions are different - which one should I be using from the command line?

**Comment by mayankbansal018** [comment]
please use one in testplatform folder. also if you are using developer cmd prompt, it's implicitly picked.

**Comment by mehagar** [comment]
Just curious - what's the difference?

**Comment by petamas** [comment]
@mayankbansal018: I know this is an old issue, but something may have changed because for me, only the `TestWindow` path is in the developer CMD prompt's PATH.

I'm using VS 2022 with this `VsDevCmd.bat` config:
```
cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\VsDevCmd.bat" -startdir=none -arch=x64 -host_arch=x64
```

(Sorry for the double notifications, I used the wrong GH account at first.)

**Comment by nohwnd** [comment]
Historically VS shipped two `vstest.console.exe`: the real one under `Common7\IDE\Extensions\TestPlatform\`, and a small forwarder stub under `Common7\IDE\CommonExtensions\Microsoft\TestWindow\` that just redirected to it. The stub existed because VS 2017 and earlier had the real binary in `TestWindow`, and when it moved in VS 2019 we kept a forwarder there (plus its `PATH` entry) so old scripts, build definitions, and the VS Developer Command Prompt would keep working. Most things have caught up since — `VsTest@2`/`@3`, the AzDO agent, and internal tooling already use `Extensions\TestPlatform` for VS 16.0+ — so we're planning to remove the stub and the `PATH` entry (the `TestWindow\` folder itself stays, it still hosts the VS Test Explorer extension) once a few remaining call sites that hardcode the old path are fixed.

If there are more issues you are having, please don't revive old closed issues, and instead open a new one and link back to the old thread if needed — it's much easier to track.
