### ISSUE TITLE
Enabling code coverage leads to errors in child processes

### ISSUE THREAD

**Issue by pleonex** [microsoft/vstest#2306]
Copy & pasting the info from #1263 as requested since the issue is still present and the workaround doesn't work.

## Description
I have a test project that targets .NET Framework 4.7.2 and .NET Core 3.1. The test starts a child process that targets also .NET Framework and .NET Core (same version and each version of the test runs the matching framework).

However, the child process that targets .NET Core crashes with the following exception:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
 File name: 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

The reason seems to be because the Code Coverage is injected into child process also.

As reported in #1263 after it was closed, we can **not** override the profiling environment variables. For instance, I tried with but the issue still happens:
```cs
process.StartInfo.EnvironmentVariables["CORECLR_ENABLE_PROFILING"] = "0";
process.StartInfo.EnvironmentVariables["COR_ENABLE_PROFILING"] = "0";
```

## Steps to reproduce
@dasMulli already provided a good reproducer:
[repro-subproc-profiling.zip](https://github.com/microsoft/vstest/files/3579844/repro-subproc-profiling.zip)

Just run it with `dotnet test --collect "Code Coverage"`

## Expected behavior
No crash, it works, there is a way to disable profiling in children process.

## Actual behavior
It crash and workaround doesn't work.

## Diagnostic logs
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
 File name: 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

## Environment
Running with `dotnet test --collect "Code Coverage"` on Windows 10 with VS 2019 16.4.2 Enterprise and .NET Core 3.1.100

**Comment by briandunnington** [comment]
@pleonex Try the other workaround mentioned in that issue: 

We found a work around that worked for us, so I will share it here in case anyone else finds it useful. The behavior of disabling the collection for child processes can also be set using the RunSettings file and that did work for us. But since we were using this in a share DevOps pipeline, we didn't want to have to have the RunSettings file copied in every project, so I was able to use the 'RunSettings command line arguments' to do the same thing. The syntax is kind of like a modified xpath query and looks like this:

`dotnet test --collect "Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.CodeCoverage.UseVerifiableInstrumentation=False DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.CodeCoverage.AllowLowIntegrityProcesses=False DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.CodeCoverage.CollectFromChildProcesses=False'`

More info on passing RunSettings via the command line can be found here: https://github.com/Microsoft/vstest-docs/blob/master/docs/RunSettingsArguments.md

_Originally posted by @briandunnington in https://github.com/microsoft/vstest/issues/1263#issuecomment-574448406_

**Comment by nohwnd** [comment]
@jakubch1 maybe you could take this? and see if that is feasible for 16.6, I am assigning it to that milestone for now.

**Comment by jakubch1** [comment]
Could you please confirm that you have this package installed:
https://www.nuget.org/packages/Microsoft.CodeCoverage/16.5.0
?

It can be easily installed by:
`dotnet add package Microsoft.CodeCoverage --version 16.5.0`

**Comment by jakubch1** [comment]
@pleonex  Closing as there is no response from you. Please reach out if you have or find the answers we need so that we can investigate further.

**Comment by pleonex** [comment]
Sorry for the late reply, for some reason I forgot about this. Today I worked again with the project I was having the issue and now I can confirm that by adding that package (well now to version 16.6.1) in the child process that my tests run (no need to add in the test project as `Microsoft.NET.Test.Sdk` does it for you), the issue is fixed :tada:

Thanks!
