### ISSUE TITLE
Webtest project is not working while run from testExplorer

### ISSUE THREAD

**Issue by vagisha-nidhi** [microsoft/vstest#2308]
**Repro steps for the issue:**

1.Install Webload component with 16.5 Preview1 build
2.Create Web performance project 
3.Record the step and Generate the Webtestcoded.cs file
4. Run web test from Test Explorer
 
**Expected:** 
Webtest test run should go through TestExplorer

**Actual:**
Web test run fails with this message:

An error occurred writing Web test result file 'C:\Users\vseqa1\source\repos\WebAndLoadTestProject1\TestResults\vseqa1_Jan20Test 2020-01-22 11_17_30\In\6633b9af-364a-4c12-8e7e-d26bfeba8b87\WebTest1.webtestResult': Could not load file or assembly 'Microsoft.VisualStudio.Telemetry, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040). The Web test result details will be lost if the Web test result viewer window is closed.

![image](https://user-images.githubusercontent.com/13175100/72894289-f7093b00-3d40-11ea-80e2-ab5c66d74ac3.png)

The assembly redirect is missing in test host exe config for Microsoft.VisualStudio.Telemetry causing the issue.

**Comment by singhsarab** [comment]
@ganesp Will be fixing this one on the adapter side.
Closing this issue here.

**Comment by gabrielamacias** [comment]
Hi @singhsarab , I'm currently getting the same error on webtests that use to run fine. Do you know how this issue was resolved? Thank you so much!
An error occurred writing Web test result file 'C:\Users\gmacia01\TestResults\gmacia01_ORIS-D-GMACIA01 2020-05-04 16_13_40\In\70fab17f-32ed-433c-a5b5-a8beafdbcbab\Furs
t.webtestResult': Could not load file or assembly 'Microsoft.VisualStudio.Telemetry, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dep
endencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040). The Web test result details will be los
t if the Web test result viewer window is closed.
