### ISSUE TITLE
Passing a normalized path to ResultsDirectory which does not exist fails on Linux

### ISSUE THREAD

**Issue by kalluri-nb** [microsoft/vstest#2352]
## Description
We have a custom msbuild scripts to build our repo which use dotnet vstest command to run the tests. Passing a normalized path to ResultsDirectory which does not exist works on Windows by creating it but fails on Linux. 

## Expected behavior
VS test should accept the normalized path instead of failing on linux

## Actual behavior
Fails with directory not found

## Environment
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

**Comment by nohwnd** [comment]
Could you post the command that you are running and the error message so we can confirm that we see the same thing please?

**Comment by kalluri-nb** [comment]
This is not an issue. The error is due to an incorrect escape characters. Our build targets construct the command based on the input. the parameter "logger=console;verbosity=minimal" is causing the failure on liunx. Is there are way to have common formats for windows and linux for the parameter which accept ';'
Thank you for your response.

**Comment by nohwnd** [comment]
@kalluri-nb it should work if you use quotes as you. See the bottom of [this comment](https://github.com/microsoft/vstest/issues/2223#issuecomment-590424026):

I can see the `-r` command not found error when I paste the code directly to command line, and it is caused by missing quotes: 
`-l:trx;LogFileName=Project_Test_Run_2020-02-11-17-05.trx -r <- incorrect ` 
`-l:"trx;LogFileName=Project_Test_Run_2020-02-11-17-05.trx" -r <- correct`

You are basically terminating the first command on the `;`, then defining an environment variable for the next command `-r` which does not exist, and so bash reports the error.
