### ISSUE TITLE
vstest result have different log format from vs2017 to vs2019

### ISSUE THREAD

**Issue by zoufeng11** [microsoft/vstest#2415]
## Description
> **IMPORTANT**: 
>Run the test with vstest.console.exe on both vs2017 and vs2019 ,the result log file shows different format with different IDE. For example (In vs2017 it shows PASSED and in vs2019 it shows √ )

## Steps to reproduce
In vs2019 run the command:
vstest.console.exe painterunittest.dll /tests:TestAdjustedDistanceBetweenGroupCopyFields
the log will be:
A total of 1 test files matched the specified pattern.
  √ TestAdjustedDistanceBetweenGroupCopyFields [32s 481ms]

In vs2017 run the command:
vstest.console.exe painterunittest.dll /tests:TestAdjustedDistanceBetweenGroupCopyFields
the log will be:
A total of 1 test files matched the specified pattern.
  PASSED TestAdjustedDistanceBetweenGroupCopyFields [32s 481ms]

## Expected
 Hope the log file generated by vstest.console.exe could show PASSED on both vs2017 and vs2019 

## Question?
>Do we have any solution that make log format same as vs2017? 

## Environment
the vstest.console.exe used by default version gernerated by visual studio version 16.4.2

**Comment by nohwnd** [comment]
We plan to address this in #1824 at least using Failed / Passed ... instead of the glyphs. We don't plan to add an option to generate log output that is exactly the same as in v2017, if you need to consume results please use some of the available loggers to get output that is meant to be processed programmatically.
