### ISSUE TITLE
Does Microsoft.NET.Test.Sdk need for Unit Test Project (.NET Framework)

### ISSUE THREAD

**Issue by AaqibAhamed** [microsoft/vstest#2422]
## Description
 I have created created Unit Test Project (.NET Framework) to my project.Does Microsoft.NET.Test.Sdk need for Unit Test Project (.NET Framework) in any ways?

## Steps to reproduce
Can I delete it from my project? Is this fine always ?.

## Expected behavior
Test should run perfectly without any issues or warnings.

## Environment
Entity Framework v4.5

**Comment by plioi** [comment]
Although this package is technically not necessary, *the things it does to your project* are necessary for Test Explorer and `dotnet test` to work. If you don't use Test Explorer or `dotnet test`, you can leave it out.

Most test frameworks' nuget packages don't list it as an automatic dependency, so in practice you *do* have to remember to include it, otherwise you'll get confusing error messages when you try to run tests. Also, you have to hope that the version you choose is truly compatible with your selected test framework. The package moves quickly, so version-to-version compatibility is a challenge.

Beware. The package actively interferes with the system under test (#2279, #2316), an unfortunate side effect of VSTest's own implementation details being copied over your own build output folder every time you build. If there were a free alternative test runner, I'd have to recommend it until the VSTest design stops doing so.

**Comment by AaqibAhamed** [comment]
But It supports only for Visual Studio Enterprise edition right?.

**Comment by plioi** [comment]
It's for everyone. I use it in Community edition all the time.

**Comment by binhtq1987** [comment]
hi plioi,

I have a concern would like to ask you. I did not install the package Microsoft.Net.Test.Sdk, but Test Explorer also works fine for me. not sure how it work, can you help me to understand this?

![image](https://user-images.githubusercontent.com/13247566/84584976-09455c00-ae3d-11ea-8d32-8c04c180440e.png)

**Comment by plioi** [comment]
Looks like your project is targeting .NET 4.5.2, the "regular old" framework. The rules are simply different for that. I believe Microsoft.Net.Test.Sdk started to show up as something end users had to deal with after .NET Core arrived.  VsTest has different code for .NET 4.5.2 and was probably able to make more assumptions on its own about how things worked.

**Comment by binhtq1987** [comment]
Thanks Patrick!

**Comment by nohwnd** [comment]
As Patrick says, testhost (the component that runs your tests) is a dependency of Test.SDK, and on netcore projects is delivered by nuget. On .NET Framework it uses the same component that is shipped with SDK (and Visual Studio) together with vstest.console.
