### ISSUE TITLE
VSTest repeatedly fails

### ISSUE THREAD

**Issue by gregpakes** [microsoft/vstest#2464]
## Description
We have had intermittent failures from the Test Assemblies task in Azure Devops using Hosted Pipelines for ages, but usually a re-run fixes it.

However, in the past 2 days these failures have increased significantly.  Hardly any of our builds succeed now.  The two errors we get are:

```
##[error]The active test run was aborted. Reason: Index was out of range. Must be non-negative and less than the size of the collection.
##[error]Parameter name: index
##[error]System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
##[error]   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
##[error]   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
##[error]   --- End of inner exception stack trace ---
##[error]   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
##[error]   at System.IO.Stream.ReadByte()
##[error]   at System.IO.BinaryReader.ReadByte()
##[error]   at System.IO.BinaryReader.Read7BitEncodedInt()
##[error]   at System.IO.BinaryReader.ReadString()
##[error]   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveRawMessage()
##[error]   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveMessage()
##[error]   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestSender.SendAfterTestRunEndAndGetResult(ITestMessageEventHandler runEventsHandler, Boolean isCancelled)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyDataCollectionManager.<>c__DisplayClass20_0.<AfterTestRunEnd>b__0()
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyDataCollectionManager.InvokeDataCollectionServiceAction(Action action, ITestMessageEventHandler runEventsHandler)
##[error]The operation was canceled.
```

and 

```
##[error]The active test run was aborted. Reason: Test host process crashed
```

I think the first error may be due to the build timeout being reached and then the process being terminated.  We set a timeout of 90 mins for our builds and it looks like the vstest task can hang/freeze/deadlock and then when it gets terminated, this error occurs.

This issue is now critical to us.

We are using "latestStable" version of the task.

It could be related to this issue, but it doesn't seem like any progress has been made there: https://github.com/microsoft/vstest/issues/2261

## Environment
Azure Devops hosted 2019 agent.

## Workaround

It appears that we get far fewer failures if we disable parallel tests.

**Comment by nohwnd** [comment]
@ShreyasRmsft have you see this happen in other pipelines?

**Comment by gregpakes** [comment]
No - It seems to be linked to the parallel option.  So it's likely our issue, but the framework is not providing any way for us to be able to identify the issue.

**Comment by nohwnd** [comment]
Did you try running it with the diagnostic logging? https://github.com/microsoft/vstest-docs/blob/master/docs/diagnose.md 

Are you running this via the dotnet task from yaml pipeline or the VSTest task from the classic pipeline?

**Comment by gregpakes** [comment]
Yes - the first error is with diagnostic logging enabled.

This is inside an Azure Devops Hosted Agent using the VSTest task using the yaml pipeline.

**Comment by gregpakes** [comment]
Could this be caused by the agent host running out of disk space?

**Comment by ShreyasRmsft** [comment]
@gregpakes it could be, and yes we have seem some intermittent instances like this before but never got around to understanding the RCA due to lack of data.

Don't think it's related to this #2261

Enable advanced diagnostics in the vstest task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops

![image](https://user-images.githubusercontent.com/25194518/84892567-70704400-b0bb-11ea-90a1-d1a5f515f7b2.png)

This should capture a memory dump in case of crashes

Also share the full zip logs with system.debug set to true. Might give us some more ideas.


> It appears that we get far fewer failures if we disable parallel tests.

This could indicate hangs in your test due to deadlocks. 


### To enable hang detection in the vstest task:

Select one of the options below based on the following:
You need only hang dump – Never
Need both hangdump and crash dump – On abort only
 
![image](https://user-images.githubusercontent.com/25194518/84892967-1de35780-b0bc-11ea-8956-a7cf1f38d062.png)

3)	Configure the runsettings to detect hangs as show in the sample commit https://github.com/ShreyasRmsft/BasicMsTestV2Tests/commit/9660a2445d934a9aa624031be8fb2aedb7ec48f6

4)	Here is a sample run https://dev.azure.com/shrer/hang%20detection/_build/results?buildId=202&view=results

5)	Here is a link to the attachments tab of the sample run https://dev.azure.com/shrer/hang%20detection/_build/results?buildId=202&view=ms.vss-test-web.build-test-results-tab&runId=1000250&paneView=attachments&resultId=0

6)	Below is a screenshot of what the attachments will look like (The last one - testhost.x86 is the dump file)

![image](https://user-images.githubusercontent.com/25194518/84893003-2dfb3700-b0bc-11ea-9cb6-e5196e1447fc.png)

**Comment by gregpakes** [comment]
@ShreyasRmsft Super useful.  I will take a look at this.

**Comment by Evangelink** [comment]
@gregpakes Are you still experiencing these intermittent failures?

**Comment by gregpakes** [comment]
Given this was 2 years ago, I'm going to have to guess.... I'm fairly sure our issue was due to the Azure Build Agents running out of disk space (I believe you get 10GB to play with).  We created our own VMSS based on the azure agent and have been using that ever since.  No issues since.

**Comment by Evangelink** [comment]
Yeah sorry for the late reply and thanks for the reply!

There were quite a few fixes that got merged in between so if you are no longer experiencing the issue, I will close the ticket. Feel free to reopen/comment if problem shows up again.

Thanks again!
