### ISSUE TITLE
dotnet test <dll> -- <RunSettingsOverrides> fails with NotImplementedException

### ISSUE THREAD

**Issue by wli3** [microsoft/vstest#2626]
---
**Issue moved from dotnet/sdk#14401**
- Please respond to @hallipr.

---

_From @hallipr on Sunday, November 1, 2020 11:56:40 PM_

When calling `dotnet test some.dll -- key=value`, I get a run time exception in CLIRunSettingsArgumentExecutor.

## Given a single test 
``` cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace Simple
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.AreEqual("Value", Environment.GetEnvironmentVariable("SomeThing"));
        }
    }
}
```

## in a simple test project, simple.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>
  
</Project>
``` 

## After `dotnet build`, this doesn't work
```
dotnet test bin\Debug\netcoreapp3.1\simple.dll -- RunConfiguration.EnvironmentVariables.SomeThing=Value 
```

```
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.CLIRunSettingsArgumentExecutor.Initialize(String argument)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory.<>c__DisplayClass20_0.<WrapLazyProcessorToInitializeOnInstantiation>b__0()
   at System.Lazy`1.PublicationOnlyViaFactory(LazyHelper initializer)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(String[] args, List`1& processors)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args)
```

## These all work
```
dotnet vstest bin\Debug\netcoreapp3.1\simple.dll -- RunConfiguration.EnvironmentVariables.SomeThing=Value 

vstest.console .\bin\Debug\netcoreapp3.1\simple.dll -- RunConfiguration.EnvironmentVariables.SomeThing=Value

dotnet test -- RunConfiguration.EnvironmentVariables.SomeThing=Value

dotnet test simple.csproj -- RunConfiguration.EnvironmentVariables.SomeThing=Value

dotnet test --no-build -- RunConfiguration.EnvironmentVariables.SomeThing=Value
```

The last one was surprising.   I assumed that --no-build would use the same codepath as `dotnet test <dll>`, but I guess not.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#14401**
- Please respond to @plemasantos.

---

_From @plemasantos on Friday, November 6, 2020 2:17:11 PM_

Bumped into the exact same problem a couple of minutes ago.

**Comment by nohwnd** [comment]
@hallipr @plemasantos  This was fixed a while ago,  it does not happen in net5.0.

> The last one was surprising. I assumed that --no-build would use the same codepath as dotnet test <dll>, but I guess not.

It won't. `dotnet test + dll` uses different path than `dotnet test + csproj` (or sln, or just a folder). `dotnet test + dll` is pretty much `dotnet vstest`, which just passes the parameters to `vstest.console`. `dotnet test + csproj` will lookup the csproj, run msbuild, pass parameters through msbuild, grab the path of the DLL from msbuild and pass it to VSTest MSBuild task, which will then, call `vstest.console`.

Before all of that on the SDK side there is a parser that tries to figure out if `dotnet test + dll` is used or `dotnet test + csproj` is used. Which is where the code was failing before we fixed how it handles inline settings when `dll` is used. 

There are no plans to port this back to net 3.1 SDK, but you can update to net5.0 and use that to build projects that target netcoreapp3.1.

**Comment by lukos** [comment]
@nohwnd I'm not sure I understand. We are running dotnet core 3 apps inside docker containers so we would need to update the base image but last time I installed the .Net 5 SDK assuming it was backwards compatible, it didn't build dotnet core and I had to install that SDK too.

Like most people who have worked in .Net for 20 years, I am utterly confused with .Net 5 anyway. .Net is a massive legacy system that MS think they can pivot every few years and to make it worse, every time they do, the party-line becomes "we are not going to fix this in current versions, change to .Net 5" as-if this is even feasible in the short-term for most of MS customers. We are already part-way through a several year migration from web forms to dotnet core so there is no way we can use .Net 5 for most things any time soon.

3.1 is supposed to be LTS anyway, which really means this needs fixing in dotnet cli for 3.1 (surely the fix is easy enough). Otherwise, it's just another reason for me to move to one of the non-.net frameworks that aren't as nice in many ways but at least they are consistent over time.

**Comment by nohwnd** [comment]
There is unfortunately a high bar for getting a fix into an older version of the SDK. 

What I meant in my comment above is that you can use 5.0 dotnet SDK to build an application that targets dotnet 3.1 runtime. You would get the newest fixes to the SDK, but you would still produce app that would happily run on 3.1 runtime. 

When you build in docker you usually have 2 different images. One for building your app, which has the SDK, you would update this one to 5. If then tried to run the app in the image it would not work, because it only has dotnet runtime 5, not 3.1. You can use the roll forward policy though to instruct dotnet to choose newer runtime if preset. 

All of this is for the image that has the SDK and builds, but not for the one that you actually ship. You are still targeting 3.1 runtime, so your normal images would use the 3.1 base that does not have the SDK at all, just runtime.
