### ISSUE TITLE
Dotnet test task can't run net48 unit tests 

### ISSUE THREAD

**Issue by eransha** [microsoft/vstest#2994]
*Type*: Question

**Enter Task Name**: DotNetCoreCLIV2

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines   
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
dynamicscrm/Solutions/CRM.BAS.FSI.PR/20210728.64

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: Hosted Windows 2019 with VS2019

## Issue Description

When trying to run unit tests which were build in a .net4.8 anycpu dll, xunit tests are being found but not running stating that:
--> task output
Starting test execution, please wait...
2021-07-28T15:47:00.5294580Z Logging Vstest Diagnostics in file: D:\a\1\s\target\release\AnyCPU\tests\diag.txt
2021-07-28T15:47:00.6936578Z A total of 1 test files matched the specified pattern.
2021-07-28T15:47:03.6525577Z Logging TestHost Diagnostics in file: D:\a\1\s\target\release\AnyCPU\tests\diag.host.21-07-28_15-47-00_71247_1.txt
2021-07-28T15:47:05.9283182Z [xUnit.net 00:00:00.02] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (32-bit Desktop .NET 4.0.30319.42000)
2021-07-28T15:47:07.7645754Z [xUnit.net 00:00:01.86] Skipping: FSIClientView.Plugins.UnitTest (could not find dependent assembly 'FSIClientView.Plugins.UnitTest, Version=1.0.0')
2021-07-28T15:47:07.8133796Z No test is available in D:\a\1\s\target\release\AnyCPU\tests\FSIClientView.Plugins.UnitTest\release\FSIClientView.Plugins.UnitTest.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
--> end of task output
[taskLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/6894761/taskLogs.zip)

### Task logs

Attached - also in the zip is the vstest diagnostics file

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

[AB#1362682](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1362682)

**Comment by eransha** [comment]
Just to give some more info on my investigations:
a. I ran the test locally on my machine using dotnet cli, vstest.console and the explorer and everything works fine.
b. I tried running in the ADO pipeline using dotnet cli, vstest tasks and even powershell to run directly the vstest.console - nothing worked.
c. In the pipeline I've tried specifying the farmework, then I tried compiling to x86 and specifying a platform, run in isolation and upgraded the dlls from framework 4.6.2 to 4.8 (and specifying the right framework) - nothing worked

**Comment by Haplois** [comment]
We verified the issue @eransha has was with the code base. Closing the issue.

**Comment by yirkha** [comment]
Hi there, fine people randomly coming here like me, hoping to find a solution at the end of the thread.

If your .NET Framework tests don't run at all in VS and when you try vstest.console.exe, you just see something like this:
```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit Desktop .NET 4.0.30319.42000)
[xUnit.net 00:00:00.42] Skipping: FooBar.Tests (could not find dependent assembly 'FooBar.Tests, Version=0.0.1')
  No test is available in FooBar.Tests\bin\Debug\net472\FooBar.Tests.dll. Make sure that test discoverer & executors
  are registered and platform & framework version settings are appropriate and try again.
```

It might be that you are working with a project that is configured to use **strong name signing**, but your dev box or CI build pipeline or whatever is not doing it properly.

When I changed at least the Tests.csproj to have `<SignAssembly>false</SignAssembly>` instead of `true` in the example above, VSTest already printed a more informative response about the actual problem:
```
  Failed FooBar.Tests.HovercraftTests.IsFullOfEels [52 ms]
  Error Message:
   System.IO.FileLoadException : Could not load file or assembly 'FooBar.Hovercraft Version=0.0.1.0, Culture=neutral,
   PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified. 
   The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.
   (Exception from HRESULT: 0x80131045)
```

Disabling signing even for the main library/project then made the tests run both from command-line and in Visual Studio UI fine. Seemed reasonable to do if building a "Debug" configuration. Another option is to temporarily use a strong name bypass, e.g. `reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\StrongName\Verification\*,31bf3856ad364e35"` (or whatever your key hash is).
