### ISSUE TITLE
Question - Why default test steps to --no-build ?

### ISSUE THREAD

**Issue by Korporal** [microsoft/vstest#3080]
This is just a question I cannot find any answer anywhere else.

GitHub offers workflow templates [here ](https://github.com/Korporal/actionstuff/actions/new)but the one for .NET includes a test step but with `--no-build `specified.

![image](https://user-images.githubusercontent.com/12262952/134969791-1d51bd78-e7b4-4cd8-866e-a4793f5f033b.png)

I'm very new to GitHub actions and spent several hours this morning struggling to understand why a project was not having its tests run.

It was only when I removed `--no-build` that I got the tests to execute.

Frankly it is absolutely bewildering to have to struggle with this kind of thing, why would one even specify `--no-build` on the project that contains the tests? how can one even execute tests without building the code in the tests?

I assumed the template was correct and had no idea that I would need to remove `--no-build`.

Is there any kind of rational explanation for this?

Thanks.

**Comment by Haplois** [comment]
I checked [this][1] run. You're only restoring and building `Nep.Scheduling.csproj`, since the test project is now built, you cannot run tests on it thus `--no-build` fails. When you remove that, we restore and build the test project for you before running the tests, that's the reason removing the argument fixes your run.

Running command in the given order, insured that restore and build only happens once, so it's faster.

[1]: https://github.com/Korporal/actionstuff/runs/3734008778
