### ISSUE TITLE
Incremental builds are broken when using the Microsoft.NET.Test.Sdk package

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#3266]
## Description
When building a test project which references the `Microsoft.NET.Test.Sdk` nuget package, incremental builds are broken because of double writes:

![image](https://user-images.githubusercontent.com/7412651/150102035-9bb14a4d-7d51-405a-93db-970de5106556.png)

## Steps to reproduce
```
dotnet new xunit -n xunittest
cd xunittest
dotnet build
dotnet build /bl
```

## Expected behavior
There shouldn't be any double writes observable in the msbuild binary log file (which can be opened with the msbuild log viewer).

## Actual behavior
The msbuild binary log viewer shows double writes (see picture above) which causes incremental builds to be broken which means that the affected test library needs to always be fully rebuilt. This is especially noticeable for customers when having many test assemblies which are built (i.e. via a sln file).

## Diagnostic logs
Not required as this is about building and not running any tests so the test adapter isn't even invoked.

## Environment
Windows, SDK version `6.0.200-preview.21617.4`.

cc @nohwnd

**Comment by nohwnd** [comment]
@drognanar this seems like something that would be right up your alley. Would you mind having a look?

**Comment by ktaeleman** [comment]
I'm noticing the same issue with 16.11.0. The double copy seems to stem from:
* `Microsoft.TestPlatform.TestHost`'s build folder being added to the `Content ItemGroup` of the test projects
* The `ResolvePackageAssets` task adding the lib folder of `Microsoft.TestPlatform.ObjectModel` due to dependency on Microsoft.NET.Test.Sdk

which both contain `Microsoft.TestPlatform.PlatformAbstractions.dll`.

**Comment by nohwnd** [comment]
@shueybubbles  We internally assigned this to @drognanar. Artur do you have some update please? The description here seems to be enough to repro find a potential fix.

**Comment by KirillOsenkov** [comment]
Ran into this as well while investigating why our incremental build was broken.

```
Encountered conflict between 'CopyLocal:/Users/kirill/.nuget/packages/microsoft.testplatform.objectmodel/17.1.0/lib/netcoreapp2.1/Microsoft.TestPlatform.PlatformAbstractions.dll' and 'CopyLocal:/Users/kirill/.nuget/packages/microsoft.testplatform.testhost/17.1.0/lib/netcoreapp2.1/Microsoft.TestPlatform.PlatformAbstractions.dll'.
Choosing 'CopyLocal:/Users/kirill/.nuget/packages/microsoft.testplatform.objectmodel/17.1.0/lib/netcoreapp2.1/Microsoft.TestPlatform.PlatformAbstractions.dll' arbitrarily as both items are copy-local and have equal file and assembly versions.
```

This is because both `Microsoft.TestPlatform.ObjectModel` and `Microsoft.TestPlatform.TestHost` NuGet packages include `Microsoft.TestPlatform.PlatformAbstractions.dll`.

The shared .dll(s) need to go into their own package(s) and a dependency needs to be added from all packages that depend on it.

**Comment by shueybubbles** [comment]
FWIW My workaround is to greatly increase the size of my build by putting the output of every test project in its own subfolder. We run the tests as part of the build, so this double write was blocking test runs due to the file copy being blocked by currently running tests.

```
<OutputPath>$(OutputPath)\$(MSBuildProjectName)</OutputPath>
```

**Comment by Evangelink** [comment]
Ping @drognanar

**Comment by drognanar** [comment]
Closing via https://github.com/microsoft/vstest/pull/3722
