### ISSUE TITLE
dotnet test does not respect LogFilePrefix

### ISSUE THREAD

**Issue by jeffreybindinganice** [microsoft/vstest#3477]
## Description
In .NET6, using the command `dotnet test -l:"trx;LogFilePrefix=/app/report/mstest/TestResults"` results in a trx file that is not put into the /app/report/mstest/TestResults folder, but just inside the unit-test project's TestResults folder.

## Steps to reproduce
1.  Create a docker file like
 ```
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine
 WORKDIR /app
 CMD dotnet test -c Release --no-restore -l:"trx;LogFilePrefix=/app/report/mstest/TestResults" solutions/ExampleSolution/$ExampleSolution.sln``
```
and build an image
2. Create a simple project with a unit-test
3. Run the build by running `docker run -v $(pwd):/app --rm -t buildImage

## Expected behavior
A .trx file in /app/report/mstest/TestResults

## Actual behavior
A .trx file in /app/ExampleTestProject/TestResults

## Environment
Container image mcr.microsoft.com/dotnet/sdk:6.0-alpine

**Comment by jeffreybindinganice** [comment]
Add additional info, when executing exactly the same commands on .NET Core 3.1 with the image mcr.microsoft.com/dotnetcore/sdk:3.1-alpine, it was behaving as expected.

**Comment by Danielku15** [comment]
Same issue for me. I dived a bit deeper and had these findings: 

* I saw [there is a validation](https://github.com/microsoft/vstest/blob/90ee608c51f07da7e6b7988b693d5e1a9d33f7a5/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs#L139-L145) if you specify both LogFileName and LogFilePrefix together. To check if the config is picked up I specified both and saw that there is an error. So its no problem on the general input. 
* Then I looked into the code that follows and saw that `LogFilePrefix` cannot be used for absolute paths. it is purely a file name prefix. 
https://github.com/microsoft/vstest/blob/90ee608c51f07da7e6b7988b693d5e1a9d33f7a5/src/Microsoft.TestPlatform.Extensions.TrxLogger/Utility/TrxFileHelper.cs#L144-L150


It seem to be the expected behavior looking at the code. If we want this to work line 144 would need to be:
```diff
- var fileNamePrefix = Path.GetFileNameWithoutExtension(fileName);
+ var fileNamePrefix = fileName;
```


I think the documentation is misleading:

> Run the tests in the project in the current directory, and log with the trx logger to files in the _TestResults_ folder, with file names that are unique for each target framework:
> .NET CLI
> `dotnet test --logger:"trx;LogFilePrefix=testResults"`
> https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test

If you look at the casing they really mean that the files will be in the usual "TestResults" folder where also other test results are. And the file names will be prefixes with `testResults` AND target framework specific parts.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead.  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli

**Comment by sinadenmark** [comment]
It's a bug - not a feature.

**Comment by nohwnd** [comment]
The logFilePrefix is meant to put a prefix into a name not change the output path. That works as far as I know.
