### ISSUE TITLE
Test dll's taking dependency on Newtonsoft.Json fail

### ISSUE THREAD

**Issue by mayankbansal018** [Microsoft/vstest#391]
## Description
> Test taking dependency on Newtonsoft.Json version other than 9.0.0.0, fail

## Steps to reproduce
> Create a test project, & add dependency on Newtonsoft.Json version(6.0.0.0)
> run the above test using vstest.console.

## Expected behavior
> The test should pass/fail.

## Actual behavior
> Error: System.IO.FileLoadException: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

**Comment by sbaid** [comment]
@codito how do we address this?

**Comment by codito** [comment]
This doesn't occur for LUT scenarios since a new appdomain is not created.

**Comment by mayankbansal018** [comment]
https://github.com/Microsoft/vstest/pull/456

**Comment by FelschR** [comment]
After I migrated my .NET Core project to csproj/MSBuild I get this error a lot.

There are a few other errors that I get which seems very similar:

`Message: System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Azure.Documents.Client, Version=1.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

`Message: System.IO.FileLoadException : Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040`

**Comment by hankbeasley** [comment]
Try adding these to your property group in test project .csproj:

` <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
 <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>`

**Comment by FelschR** [comment]
@hankbeasley This did it!!! Thanks a lot! I spent hours on this -_-
Is there any explanation why this only fails when running the tests via VS2017?

**Comment by codito** [comment]
Related to #428

**Comment by Faizan2304** [comment]
Issue:: If a user's project is taking a dependency on Newtonsoft.Json with version `6.0.5` and in test code he is using Newtonsoft API's inside an appdomain. Appdomain uses config file of the parent process if not provided any, so here it will use testhost config file which has binding redirect `<bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />`. Since the user's projects is dependent on Newtonsoft.Json of version `6.0.5` their tests break because of the redirection.
In the TestPlatform repo: Microsoft.TestPlatform.CommunicationUtilities depends on Newtonsoft.Json`(8.0.3)` and Microsoft.TestPlatform.CrossPlatEngine depends on Microsoft.Extensions.Dependencymodel which depends on Newtonsoft.Json `(9.0.1)`. So testhost ends up having Newtonsoft.Json.dll of version `9.0.1` in their publish package. Since testhost uses CommunicationUtilities (and does not use that part of CrossPlatEngine which uses Newtonsoft.Json of version `9.0.1`) so it needs Newtonsoft.Json.dll of version `8.0.3` along with it.
Hence, need to copy Newtonsoft.Json.dll of version `8.0.3` to test testhost publish directory. This is however very much dependent on the CrossPlatEngine code running in testhost to not call into APIs specific to `9.0.1`.
