### ISSUE TITLE
IsValidArchitectureMuxer does not return a valid architecture on Unix systems

### ISSUE THREAD

**Issue by mmalandra-kb4** [microsoft/vstest#4042]
## Description
When attempting to use vstest.console on unix, you will get an Incompatible architecture muxer error due to the IsValidArchitectureMuxer in the DotnetHostHelper only handling Windows and OSX.

https://github.com/microsoft/vstest/blob/e14a3664fb0ebe7e02a3cd6cc878e7619adf0703/src/Microsoft.TestPlatform.CoreUtilities/Helpers/DotnetHostHelper.cs#L422

## Steps to reproduce
1. Build vstest.console for linux-x64
2. Run vstest.console on a unix system

## Expected behavior
Test should run

## Actual behavior
Test fails due to an incompatible architecture muxer.

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
Occurs on any unix system with version 17.3.0.

**Comment by mmalandra-kb4** [comment]
Simply by adding another branch to the if statement in DotnetHostHelper.IsValidArchitectureMuxer as follows allows vstest.console to run as expected:
`        else if (_environment.OperatingSystem == PlatformOperatingSystem.Unix)
        {
            muxerPlatform = PlatformArchitecture.X64;
        }`

**Comment by MarcoRossignoli** [comment]
Why you need to use `vstest.console.dll` directly? What's your scenario?
The code handle only Windows/OSX because was done to support architecture switch(`--arch`) that's not fully supported on linux atm.

Code in your sample is not correct in all cases, architecture depends on process(and so on the image to run) and not on operative system, OS can implement virtualization.

**Comment by mmalandra-kb4** [comment]
AFAIK, the vstest.console.dll is only available on the dotnet sdk. we wanted to directly call vstest.console.dll on the runtime to reduce the image size that we're using on our docker containers.

**Comment by MarcoRossignoli** [comment]
got it, it's a non supported scenario at the moment, SDK and vstest.console.dll are logically linked together and we're passing expected hidden parameter between the two. So it's possible that some feature will fail.

For now we don't plan to add that branch because we don't expect this usage and add a "default" branch could cause inconsistency and confusion.
