### ISSUE TITLE
Issue with test filtering

### ISSUE THREAD

**Issue by Evangelink** [microsoft/vstest#4271]
That's what I'm trying to find out I guess. It seems that the fix to the problem was to revert the name changes that was done:

```
// This causes compatibility problems with older runners.
// return string.IsNullOrWhiteSpace(this.TestMethod.ManagedMethodName)
//      ? this.TestMethod.Name 
```

Even now the display name code still has above code, but other code has been added to the ToTestCase() function to append some more information.

Basically,
MSTest.TestAdapter version 2.1.0 had this output:
vstest.console.exe /TestCaseFilter:"FullyQualifiedName=Namespace.TestName"

Whereas,
MSTest.TestAdapter version 3.0.0 had this output:
vstest.console.exe /TestCaseFilter:"FullyQualifiedName=Namespace.TestName **(input)**"

Which causes the error 
"##[error]Incorrect format for TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed."

So i'm guessing that the failed test function name being returned to the ADO Task now has **(input)** which is causing it to fail.

So is this an ADO Task issue where they now have to escape the parenthesis? For example, 
vstest.console.exe /TestCaseFilter:"FullyQualifiedName=Namespace.TestName **\\(input)\\**"

_Originally posted by @iesmat in https://github.com/microsoft/testfx/issues/793#issuecomment-1372546543_

**Comment by nohwnd** [comment]
The error above about missing | or & operator is caused by `( )` not being escaped, so the filter interpreter thinks they are part of the filter, and not part of the name. And so it expected an operator before them.

When you escape `( )` it still does not work because the FullyQualified name probably does not include the parameters. 

```cs
// file UnitTest1.cs
namespace mstest63;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    [DataRow(1)]
    [DataRow(2)]
    public void TestMethod1(int a)
    {
    }
}
```

```cs
// file Usings.cs
global using Microsoft.VisualStudio.TestTools.UnitTesting;
```

```
dotnet vstest S:\t\mstest63\bin\Debug\net8.0\mstest63.dll 
	/testcaseFilter:"FullyQualifiedName~2"
```

Should run the second test if there was the parameter in the name, but it runs 0 tests. 

Name runs 1 test correctly, but does not allow to specify the test with fully qualified name.
```
dotnet vstest S:\t\mstest63\bin\Debug\net8.0\mstest63.dll
	/testcaseFilter:"Name~2"
```

And DisplayName filter just plain does not work because it runs 0 tests even when I look for `1` which is in all test names.


For XUnit, similarly FullyQualified name is not including the parameters, DisplayName filter **works** and allows to run just one test with the fully qualified name, and Name filter does not work at all.

**Comment by nohwnd** [comment]
This is how mstest shows the tests on discovery: 

```
The following Tests are available:
    TestMethod1 (1)
    TestMethod1 (2)
```

This is how xunit shows them:
```
The following Tests are available:
    xunit11.UnitTest1.Test1(a: 1)
    xunit11.UnitTest1.Test1(a: 2)
```

Xunit implementation of DisplayName filter seems to be consistent with what is shown on discovery. MSTest seems not.

**Comment by nohwnd** [comment]
Not being able to use `DisplayName` on mstest, and `Name` on xunit is explained by this table: 

![image](https://user-images.githubusercontent.com/5735905/214556651-0f224aee-49b7-4aaf-8997-141563819bcb.png)

Thed don't support them. The filterExpression is probably generic and not throwing on unknown identifier because the filter can contain filters that are specific to multiple frameworks, to allow filtering for a multi-test-framework solution.

https://github.com/Microsoft/vstest-docs/blob/main/docs/filter.md

**Comment by nohwnd** [comment]
@Evangelink  this seems to be mstest problem. The filter is passed correctly once () are escaped correctly. 

Maybe the error message in vstest could be improved a bit to point out that literal `( )` need to be escaped. WYDT?

**Comment by Evangelink** [comment]
If I try to summarize here. Given the test class:

```csharp
[TestClass]
public class UnitTest1
{
    [TestMethod]
    [DataRow(1)]
    [DataRow(2)]
    public void TestMethod1(int a)
    {
    }
}
```

You can do:

- `dotnet test --filter "FullyQualifiedName=TestProject2.UnitTest1.TestMethod1"` which will run the 2 tests because they both have the same fully qualified name (parameters are ignored).

- `dotnet test --filter "Name=TestMethod1 \(1\)"` which will run only 1 test where the value is `1`.

- If you don't escape the parenthesis and try to run `Name=TestMethod1 (1)`, you will get the following error `Incorrect format for TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.` because vstest filter system thinks the parenthesis are there to help with OR and AND operators between condition.

**Comment by iesmat** [comment]
Summary seems correct.
Is it possible to forward this issue to the VSTest **ADO** team to update to use the proper escape for the filters they are passing to vstest? Or is this the correct team already?

**Comment by nohwnd** [comment]
This is very similar problem: https://github.com/microsoft/azure-pipelines-tasks/issues/13130
