### ISSUE TITLE
Best practices for detecting when the test host crashes

### ISSUE THREAD

**Issue by adcloeshelle** [microsoft/vstest#4336]
## Description

We recently had a unit test with a StackOverflow, but our CI system didn't detect this issue due to the test host crashing. Is there any best practices for catching test host crashes so our CI system can find out that the test host crashed and not all tests were run? I see the --blame option - should we always run our test suite with `--blame`? Is there a performance concern with that?

**Comment by MarcoRossignoli** [comment]
@adcloeshelle here you can find the troubleshooting guide to get logs and dumps https://github.com/microsoft/vstest/blob/main/docs/troubleshooting.md

> should we always run our test suite with --blame? Is there a performance concern with that?

@tommcdon are there performance penalties to run application under `DOTNET_DbgEnableMiniDump=1` https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash?

**Comment by tommcdon** [comment]
> @tommcdon are there performance penalties to run application under DOTNET_DbgEnableMiniDump=1 https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash or under procdump.exe(I know that in this case it's attaching as a debugger and so I expect some kind of interaction/influence with the target process threading)?

The runtime launches createdump when there is an unhandled exception occurring and blocks coreclr shutdown while a  dump is being collected.  Createdump will suspend all of the threads in the process and then enumerate the memory while writing to disk.  Otherwise there should be no performance penalty to normal .NET code execution.
Adding @mikem8361 in case there are other details that might be relevant

**Comment by MarcoRossignoli** [comment]
For `procdump.exe` that it attaches as debugger, the code will run 99% of the speed because each exception will suspend/resume the process for a ~msec and in case the code contains `IsDebuggerPresent()` that  code path will be invoked.

@adcloeshelle I'm going to close this issue because we answered, feel free to re-open if needed.
