### ISSUE TITLE
17.6.x consumes lot of CPU

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#4553]
When multiple test projects are run in sequence, vstest.console can consume a lot of CPU because it is constantly polling for data from testhost that is started but not executing yet. 

This was mitigated by disabling testhost pre-start in the linked PR and inserted into VS 17.6.4. This regression was introduced in 17.6.0.

**Comment by cremor** [comment]
I just found this entry in the [Visual Studio 17.6.4 release notes](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.6.4):

> When multiple test projects are run in sequence, vstest.console can consume a lot of CPU because it is constantly polling for data from testhost that is started but not executing yet. This was mitigated by disabling testhost pre-start. This regression was introduced in 17.6.0.

I assume that means this issue?
If yes, does that mean the issue was fixed with a Visual Studio update? So we don't have to wait for an eventually upcoming version 17.6.3 of the NuGet package `Microsoft.NET.Test.Sdk`?

**Comment by nohwnd** [comment]
@cremor	Yes. This issue is impacting vstest.console and it's consumers (such as dotnet test), we've inserted into VS and dotnet SDK, but did not yet release 17.6.3 nuget package, which would fix users that are using VS platform Installer task. 

This issue has no impact on Microsoft.NET.Test.Sdk, because that package is used to ship testhost.
