### ISSUE TITLE
vstest.console not able to load Microsoft.DiaSymReader during execution

### ISSUE THREAD

**Issue by payn-git** [microsoft/vstest#4716]
## Description
We have .NET Framework Test projects which are referencing NuGet packages for NUnit and NUnitTestAdapter. All those test project are able to run in VS 2022 correctly when they are setup that way. When we will try to run same test projects over vstest.console on same computer where VS itself is installed we will end up in situation where runner will say that binaries dont contains any tests.  If NuGet Microsoft.NET.Test.Sdk is added to single test project in solution (8 test projects in total) and recompiled. vstest.console is miraculously able to run all tests from all projects afterwards.

However, when we are trying to do exactly same in AzureDevops pipeline while we are using VSTest@2 it doesnt matter if Microsoft.NET.Test.Sdk is or is not included in single or all projects. Execution will fail with error "Failed to load extensions from file 'D:\B\2\4\s\bin\x64\Debug\NUnit3.TestAdapter.dll'. Please use /diag for more information." 

In detailed log (we can provide it) following errors are logged.
TpTrace Verbose: 0 : 4640, 1, 2023/10/20, 08:44:40.104, 7243901507794, vstest.console.exe, MetadataReaderExtensionsHelper: Discovering extensions inside assembly 'Microsoft.DiaSymReader, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' file path 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\Extensions\Microsoft.DiaSymReader.dll'
TpTrace Information: 0 : 4640, 1, 2023/10/20, 08:44:40.104, 7243901544329, vstest.console.exe, AssemblyResolver.OnResolve: Microsoft.DiaSymReader.Native.amd64: Resolving assembly.
TpTrace Information: 0 : 4640, 1, 2023/10/20, 08:44:40.104, 7243901545205, vstest.console.exe, AssemblyResolver.OnResolve: Microsoft.DiaSymReader.Native.amd64: Searching in: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\Extensions'.
TpTrace Information: 0 : 4640, 1, 2023/10/20, 08:44:40.119, 7243901706136, vstest.console.exe, AssemblyResolver.OnResolve: Microsoft.DiaSymReader.Native.amd64: Failed to load assembly. Reason:System.BadImageFormatException: Could not load file or assembly 'Microsoft.DiaSymReader.Native.amd64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'Microsoft.DiaSymReader.Native.amd64.dll' ---> System.BadImageFormatException: Could not load file or assembly 'Microsoft.DiaSymReader.Native.amd64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'Microsoft.DiaSymReader.Native.amd64.dll'

   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.AssemblyResolver.OnResolve(Object sender, AssemblyResolveEventArgs args)

## Expected behavior
Tests will run.

## Actual behavior
vstest.console not able to run tests as its not able to load Microsoft.DiaSymReader

## Environment
VS 2022 17.6 when running from VS itself or commandline. Or VSTest@2 with 2022 17.6 build setup.

[TestRunDiag.txt](https://github.com/microsoft/vstest/files/13054211/TestRunDiag.txt)

**Comment by nohwnd** [comment]
Hello, when you run with diag multiple files are created. The one you posted is for vstest.console, please provide the file that has *.host.* in the name.  

You can also search the file for ITestDiscoverer, and failed to load. There should be the reason why it cannot load NUnit.

**Comment by payn-git** [comment]
When vstest fail, it will show message to enable diag option to provide detailed information why it failed. So that's what I attached as that's what tool told me to do :).  I can specify file location for that diag file. But I cant find your ".host" or "ITestDiscoverer" file anywhere. Where they supposed to be created ?

**Comment by nohwnd** [comment]
Yes you did the right thing, but there should be more files in the same folder where it created the file you posted. I see in the file you posted that it is starting testhost. If you can reproduce this locally. Please just run it with `--diag logs/log.txt` and post the whole `logs` folder.

**Comment by payn-git** [comment]
Please see attached files from local run as well as from Azure pipeline.

[LocalRunVS2022.zip](https://github.com/microsoft/vstest/files/13168751/LocalRunVS2022.zip)
[AzurePipeline.zip](https://github.com/microsoft/vstest/files/13168752/AzurePipeline.zip)

**Comment by nohwnd** [comment]
The host log says:

Failed to load extensions from file 'D:\B\2\5\s\bin\x64\Debug\NUnit3.TestAdapter.dll'.  Skipping test extension scan for this file.  Error: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)


This is an error message that you would see when .NET Core dll is trying to load into .NET Framework process. Your testhost is .NET Framework 48, because your project is detected as .NET Framework 48.

So there are 3 options: 

1. You are stripping TargetFrameworkAttribute from your test dll somewhere in build, and it is detected incorrectly as .NET framework. This is unlikely because I would expect to see .NET Framework 462 host in that case. You can double check by opening your dll in ilspy.
![image](https://github.com/microsoft/vstest/assets/5735905/45f151a1-56a4-44f6-8a0f-bb5a3e70cd61)


2. You are mixing your dependencies somewhere in the build. But I don't see any of your test dlls in this run being detected as .NET (Core). So I don't know which project that dll would come from.

3. VStest is scraping all your test projects for dlls and links this into your project. Also unlikely, the DLL is in the same folder as your test projects. 

So I would start by downloading the folder of your build, and double checked with ILspy (as shown above), what is the target framework of you test dll, and what is the target framework of the NUnit3.TestAdpater.dll in that same folder. 


repro: 

You can simply dotnet build, and then copy the nunit3.testadapter.dll from the net8.0 bin to net48. Run with `dotnet test <path to the dll> --diag:logs\` and you will see the same error in log. 
[mixup.zip](https://github.com/microsoft/vstest/files/13186235/mixup.zip)
