### ISSUE TITLE
The HTML report has visual glitches (stairs effect) with the .NET 8 SDK

### ISSUE THREAD

**Issue by 0xced** [microsoft/vstest#4754]
## Description

The VSTest HTML report renders with visual _stairs_ glitch, better described with this screenshot.

<img width="1140" alt="Screenshot 2023-11-18 at 15 04 09" src="https://github.com/microsoft/vstest/assets/51363/55169b12-aa7d-4a8c-b1bb-ec1fad237cf5">

## Steps to reproduce

1. Checkout https://github.com/serilog-contrib/serilog-formatting-log4net/commit/3b1bdae0c71c4ec373d95e6fa8d53f42eb27c099

2. Update the `global.json` file from `6.0.400` to `8.0.100`

3. Run `dotnet test`

4. Open the `coverage/net6.0/results/TestResults-net6.0.html` file, which should be equivalent to the above screenshot.

## Expected behavior

The HTML report renders nicely. Note that this is what happens withe the .NET 6 SDK (i.e. without touching the `global.json` file).

<img width="1140" alt="Screenshot 2023-11-18 at 15 01 03" src="https://github.com/microsoft/vstest/assets/51363/2c14ee96-2e1f-4fa8-87bd-e2b0f2e50a92">

**Comment by nohwnd** [comment]
Wow, did not know we have an opposite Star Wars mode.

**Comment by nohwnd** [comment]
Reverting this commit fixes the issue: 

https://github.com/microsoft/vstest/pull/4576/files

**Comment by nohwnd** [comment]
The issue was that with the new writer the settings from xslt were not copied, and it output a self-closing <div /> tag when there was no content in error-info. This is a valid XML syntax but not valid HTML syntax. 

![image](https://github.com/microsoft/vstest/assets/5735905/928fe59a-e47e-4707-937c-57cf506c52f9)

Same issue solved on SO: https://stackoverflow.com/questions/71357056/c-sharp-xslt-transformer-uses-self-closing-html-tags-which-are-invalid
