### ISSUE TITLE
xUnit.net theories not reporting correctly in VS2017 w/ UWP

### ISSUE THREAD

**Issue by bradwilson** [Microsoft/vstest#492]
## Description
Theories (data-driven tests) are not reporting correctly with UWP in VS2017. They are reporting correctly in older versions of Visual Studio. They are also correctly reporting for desktop and .NET Core projects in VS2017.

## Steps to reproduce
Using VS2015 SP3, clone https://github.com/xunit/xunit.integration (branch `master`), and build and run tests. All UWP tests report as expected:

<img src="https://cloud.githubusercontent.com/assets/16944/22940820/09d13054-f298-11e6-9823-5d6ed41e75e1.png" width="244" />

Using VS2017 RC4, clone https://github.com/xunit/xunit.integration (branch `vs2017`), and build and run tests. UWP theories are running, but fail to report:

<img src="https://cloud.githubusercontent.com/assets/16944/22940847/1fb6c578-f298-11e6-83e5-6f69897f47b5.png" width="247" />

Output window shows that the tests are being reported but ignored:

<img src="https://cloud.githubusercontent.com/assets/16944/22940852/230c20f6-f298-11e6-8710-82131b9fd1ac.png" width="860" />

## Expected behavior
Expect all UWP tests to report results.

## Actual behavior
Theory-based tests in UWP are not reporting results. Theory-based tests in desktop and .NET Core are reporting results as expected.

## Environment
Windows 10, latest patches. VS2015 SP3, VS2017 RC4.

**Comment by saikrishnav** [comment]
@bradwilson If you do "RunSelected" on particular project, then there is no issue. However, issue reproes if you do RunALL on all projects. Investigating.

**Comment by saikrishnav** [comment]
@bradwilson When the error occurs during RunAll - I see this error in Tests output window. Looks like TestCase  deserialization failing due to parameterless constructor. It is possible that changes to objectmodel in VS 2017 are causing this (just a hypothesis). Still investigating. 

[xUnit.net 00:00:02.4542841] Unable to de-serialize test case DeserializationFailureTests.TheoryDataSerializerIsBroken(item: BadTheoryItem { Value = 42 }): System.InvalidOperationException: Could not de-serialize type 'BadTheoryItem' because it lacks a parameterless constructor.

Server stack trace: 
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestFrameworkExecutor.Deserialize(String value)
   at Xunit.Xunit2.Deserialize(String value)
   at Xunit.XunitFrontController.Deserialize(String value)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.Deserialize(LoggerHelper logger, ITestFrameworkExecutor executor, TestCase testCase)

**Comment by saikrishnav** [comment]
@bradwilson 
RunALL tests is returning test results with different displyname and testcase ID - than what the discovery stamped on those tests. So, TestExplorer is not able to reconcile the test result with test case. As you can see below, there is no match and displayname-fqn is coming wrong. I cannot tell why this is specifc to VS 2017 as we do not generate either displayname or ID for Xunit tests. 

During Discovery, Xunit Theory tests are coming with following DisplayName/FQN,  TestCase.ID (Guid): 
```
BasicTests.Theory (aa18512db414ab7e3e247252fb67bb123abbd227), 7a9a0e5b-a76d-6d5f-9094-e2cf02dac011, 1073177365
BasicTests.Theory (3a76fe69f41f568807e510cd91a3341e0aa16363), 3dc768cd-bca4-bef2-077c-e5c19645e6fc, 1684264643
BasicTests.Theory (923331978d9e2075a544ea979da600dadd044e1f), e839e55c-12bd-46a8-180d-b34fa2ab38e9, 1233429277

```
During RunALL, Xunit Theory tests are coming with different displayname and TestCase.Id:
```
BasicTests.Theory (6d790a8ce1d8201159f76e519ea7679e36245d0b), 091d8235-8ed3-3c10-e30a-210866752063'.
BasicTests.Theory (7f00a5924a0085e3a88f15f877d695f8261af67d), 6a1fbf6c-d581-8cf4-cbca-ae339a29224f'.
BasicTests.Theory (ca2a95e31050ba6557fad5f3e1e6874398456240), 729ec1c6-6889-5434-04ed-a5b61e22d9bf'.
```

**Comment by bradwilson** [comment]
The problem is that the core types are no longer defined in `mscorlib` when running inside of UWP; instead they are defined in `System.Private.Core` (located at `C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.1.1_1.1.24920.0_x86__8wekyb3d8bbwe\System.Private.CoreLib.ni.dll` on my machine).

This causes the serialization of the theory data to fail, because on one side the serialized ElementType of the array is, for example, `System.Int32`, whereas on the UWP side it's `System.Int32, System.Private.CoreLib`. You can see the special case code here:

https://github.com/xunit/xunit/blob/d9e3e4c10011cd76574a006214bab51093c4c1e4/src/common/SerializationHelper.cs#L227-L228

```csharp
if (string.Equals(assemblyName, "mscorlib", StringComparison.OrdinalIgnoreCase))
    return typeName;
```

There are several mysteries to me here, not the least of which are:

* Why is this unique to VS2017?
* Why is this assembly not called `mscorlib` like it is everywhere else?
* What other "special names" am I going to be missing now?
* Why does it appear that .NET Core 1.1 assemblies are being used in UWP?

**Comment by saikrishnav** [comment]
@unniravindranathan @terrajobst 
Adding Unni and Immo to answer above questions, as these are really specific to .Net core and UWP.

**Comment by onovotny** [comment]
One theory….. That doesn’t explain why it's working on 2015:

Discovery is done using the desktop framework, which is wrong and we've complained about before.

Run All, as part of execution, runs in the UWP AppContainer and reruns discovery (again, inefficient, you know the tests, you should provide the list) before execution. This time though, the assembly names are different and thus the id changes.

Doesn't explain why it works on 2015 though.

Sent from my Windows 10 phone

**Comment by bradwilson** [comment]
The assemblies are definitely different in VS2017, whereas in VS2015, it's `mscorlib` on both sides (Desktop and UWP).

**Comment by onovotny** [comment]
So the big question is what changed in this area with the way the tests are discovered and/or run between 2015 and 2017 for UWP projects?

**Comment by terrajobst** [comment]
@bradwilson @onovotny 

I don't know enough about how xUnit and VS Test Explorer integrate. Are you serializing in .NET Core and then deserialize back on .NET Framework?

**Comment by bradwilson** [comment]
@terrajobst This is not about serialization, per-se, but the definition of the types: `System.Int32, mscorlib` on desktop vs. `System.Int32, System.Private.CoreLib` on UWP, which appears to be unique to VS2017.

**Comment by terrajobst** [comment]
UWP has two runtimes, MRT (when AOT compiling) and CoreCLR (when debugging). We've changed the implementation assembly of CoreCLR from `mscorlib` to `System.Private.CoreLib` a while ago (not sure when). Of course, `mscorlib` still exists but it type forwards to `System.Private.CoreLib`. It should be an implementation level change that doesn't affect you.

So how does this change break you?

**Comment by bradwilson** [comment]
It happens during our serialization of theory parameter values, which is used to generate the unique ID of the test method. When one side serializes the type name as `System.Int32` and the other side serializes it as `System.Int32, System.Private.CoreLib`, the unique IDs don't match.

We have to add line 228 here as a result: https://github.com/xunit/xunit/blob/master/src/common/SerializationHelper.cs#L227-L229

**Comment by codito** [comment]
This rootcause is external to vstest. Will close this one. Please create an issue in corefx if this requires follow up.
