### ISSUE TITLE
Dump file not created when process crashes

### ISSUE THREAD

**Issue by AArnott** [microsoft/vstest#5121]
I have a particularly annoying bug that frequently crashes the test runner in Azure Pipelines but thus far hasn't repro'd locally on a dev box. I need a dump of the process to investigate, but no dump in produced.

[Here is a sample crash](https://dev.azure.com/azure-public/vside/_build/results?buildId=20341&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=09bcc455-e770-5f06-0452-f817068d38b7&l=111).

[The command that runs the test](https://github.com/microsoft/vs-streamjsonrpc/blob/0361871a9d8809b28d7e0efa0186642bba03b4af/azure-pipelines/dotnet-test-cloud.ps1#L48-L58) includes `--blame-crash` and other switches. 
On Windows agents [I also acquire `procdump`](https://github.com/microsoft/vs-streamjsonrpc/blob/0361871a9d8809b28d7e0efa0186642bba03b4af/init.ps1#L92-L94) and set the `PROCDUMP_PATH` environment variable.

In the cases I have, the crashes happen on linux. What additional steps must I take in my pipeline to get a dump collected?

.NET SDK 8.0.300
.NET 8.0.6

**Comment by nohwnd** [comment]
There are no additional steps for you to take, dumps on .NET rely on the built-in dumping capabilities of .NET. 

All the `[createdump]` messages are coming from there, and so this issue is probably better reported on dotnet/runtime ?

If it also crashes on Windows you could force dotnet test to use ProcDump also for .NET. 

`VSTEST_DUMP_FORCEPROCDUMP=1`

and tell it to use managed dumps: 

`VSTEST_DUMP_PROCDUMPARGUMENTS="-ma -e"`

and also specify `--blame-collect-always` because otherwise it will most likely delete the dump you make.

**Comment by AArnott** [comment]
Thanks. I've filed https://github.com/dotnet/runtime/issues/104256.
