### ISSUE TITLE
Microsoft.NET.Test.Sdk package is not transitive and is required by every test project

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/vstest#515]
I'm having issues (https://github.com/Microsoft/vstest/issues/446#issuecomment-280414567) where my project is not discovering tests unless I reference the Microsoft.NET.Test.Sdk in every test project.... I have a base test class library that references it and this should be all I need to get everything working (it works for .net full framework project references, but if I have a project target .netcoreapp and net46 I have to have this package for them to be discoverable)

https://github.com/exceptionless/foundatio

**Comment by mayankbansal018** [comment]
@niemyjski The dependencies are now transitive, so if you reference it in base class library they are picked up by other projects. That being said in case of VS IDE the tests are still not discovered for such projects since they do not get "TestContainer" capability which comes from "Microsoft.NET.Test.Sdk.props" file present in Microsoft.NET.Test.Sdk. 

The CLI scenario works now both discovers, & executes tests, but the VS IDE discovers test only from projects which contain this capability. & project not directly referencing "" do not get this capability.

Although IMO if you want to keep the dependency on nugets common through your projects, the correct way to do so would be via keeping a common targets, & props file which will bring in those dependencies for all your projects.

**Comment by mayankbansal018** [comment]
@niemyjski , can you please review my above comment, & let us know if it sounds reasonable to you?

**Comment by mayankbansal018** [comment]
@niemyjski, I'm closing this issue, please reopen if your issue is not resolved as per my comment[https://github.com/Microsoft/vstest/issues/515#issuecomment-347825351](url)
