### ISSUE TITLE
Test discovery fails on .Net Core 2.0 

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#547]
## Description
TestExplorer fails to discover tests on .Net Core 2.0 .The output window would show “0 tests” discovered.

**Comment by Faizan2304** [comment]
Update: From commandline discovery is working fine. Since Netcoreapp2.0 in not in nugget we need to add a default.config file with content
<packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>

Till today VS from d15prerel branch doesn't have template for template 2.0. Trying to create a local machine which can create project targeting netcoreapp2.0.

**Comment by Faizan2304** [comment]
Discovery is working now on VS version 15.1 (26406.1) vsuwpt
