### ISSUE TITLE
Test Platform should provide serialization APIs

### ISSUE THREAD

**Issue by genlu** [Microsoft/vstest#549]
Currently, for the consumers of test objects created by Test Platform (e.g. `TestCase`, `TestResult`, etc) to pass them around, they need to:

1. serialize those objects themselves, where omitting some data (intentionally or not) might cause functionality issues in other components (e.g. displaying results in test window)
2.  use existing code such as 
https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CommunicationUtilities/Serialization/TestObjectConverter.cs
but this is implementation details of test platform which in my opinion would be better hidden away from users (plus this would cause the user to add an extra dependency on json.net).

**Comment by codito** [comment]
We've to find out how to do this without adding coupling.

* Is the expectation to serialize to JSON?
* If so, test platform may use a different serialization setting than that of the consumer. How can we standardize this without leaking a implementation dependency (on JSON.net or similar)?
* How would the caller use it? Is `TestCase` part of some other container object in the consumer? In that case, will consumer always represent `TestCase` as a string in the container? Will this add perf overhead since previously consumer was just serializing from string representation of an entire container versus now they have to first get the string of `TestCase` and then call an API to deserialize it?
*  Will it help if the `TestCase` JSON is well documented and standardized? Even then, `TestObject` is extensible (in terms of `TestProperty`), probably consumer will need to query that and serialize/deserialize. I am thinking `TestCase` as similar to input/output of any REST API; as long as the spec is well documented, any client can implement its own serialization primitive (JSON, BSON, XML etc..)

**Comment by genlu** [comment]
- I think it would be reasonable to expect the API to convert those object to/from some universal types, such as `string` or `byte[]`.
- Then, how serialization is done in test platform would be irrelevant to the users, as long as they get some data back that can be easily passed around, no matter what scheme they choose to use.
- Not sure I understand you point correctly, but I fail to see why calling a deserialization API would cause perf overhead (other than the method call itself), after all, the same amount of serialized data need to be deserialized, either by user himself or through test platform API. 
- Sure, it would help if the user need to do that for some reason, e.g. store them in human readable format.

**Comment by genlu** [comment]
A related note: why TestPlatform picks JSON for serialization? I believe no one is consuming the json text, it is always just sent over the wire as raw bytes, is that correct? We would be able to see improvements (both size and speed) by switching to libraries like protobuf or simply handling serialization ourselves (directly into byte[])

**Comment by genlu** [comment]
@ManishJayaswal

**Comment by codito** [comment]
> A related note: why TestPlatform picks JSON for serialization? I believe no one is consuming the json text

JSON protocol is available to editors: https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0007-Editors-API-Specification.md. `TestCase`, `TestResult` are documented at the end of that doc.

**Comment by codito** [comment]
> How would the caller use it? Is TestCase part of some other container object in the consumer? In that case, will consumer always represent TestCase as a string in the container? Will this add perf overhead since previously consumer was just serializing from string representation of an entire container versus now they have to first get the string of TestCase and then call an API to deserialize it?
> > Not sure I understand you point correctly, but I fail to see why calling a deserialization API would cause perf overhead (other than the method call itself), after all, the same amount of serialized data need to be deserialized, either by user himself or through test platform API.

Adding an example to help understand better (correct me if details are missing):
1. (LUT)Entrypoint app asks Test Platform (using TranslationLayer) to run a test assembly, the discovery/execution results come back as `TestCase`, `TestResult`  --> there a Deserialization from String to TestResult object here within TranslationLayer
2. Entrypoint app applies some business logic on the objects received
3. It sends them over the wire to VS  --> Serialization happens here
4. At VS, again the TestCase, TestResult objects are created   --> Deserialization happens here

There is a cost of Deserialization/Serialization here (in 1, 3, 4). What is the nature of step (2)? Does it mutate the `TestCase` and `TestResult` objects? I'm asking because if it's a readonly operation, the raw string from (1) could be passed directly in step (3).

How does communication in step (3) happen? Which APIs are used to pass in the result?

**Comment by genlu** [comment]
The steps you listed above is correct, and step (3) indeed is readonly. LUT has its own serialization logic (directly into byte[]), and it selects data we believe is required by Test Explorer (currently still missing some properties, hence this issue I created). So if we want to pass raw string to VS, then we definitly need the deserialization API from test platform, since the deserialization on VS end is handled by LUT as well.

**Comment by pvlakshm** [comment]
Closing this; reactivate if still required.
