### ISSUE TITLE
Error when debugging xunit test on netcoreapp1.0

### ISSUE THREAD

**Issue by JamesNK** [Microsoft/vstest#588]
## Description
An error occurs when trying to debug an xunit test on a netcoreapp1.0 test project

## Steps to reproduce
1. Clone https://github.com/JamesNK/Newtonsoft.Json
2. Open Newtonsoft.Json.Roslyn.sln
3. Edit Newtonsoft.Json.Tests.Roslyn.csproj so TargetFrameworks = netcoreapp1.0
4. Open test class, right click test and choose debug

## Expected behavior
Test runs with debugger attached. Breakpoints are hit.

## Actual behavior
An error dialog is displayed by VS2017

![image](https://cloud.githubusercontent.com/assets/303201/23779839/bd5508ea-05a7-11e7-9d85-1f5c74f40cfa.png)

## Environment
VS2017 RTM

**Comment by smadala** [comment]
@JamesNK I am not able to repro it, Tried to debug all and debug following classes
`Newtonsoft.Json.Tests.Bson.BsonReaderAsyncTests`, `Newtonsoft.Json.Tests.Utilities.ConvertUtilsTests`  debugger attached and breakpoins were hit.

Can you please specific which test class you ran?
Is it repro always?

Heads up: There is bug for working directory comes as C:\Windows\system32 for debug scenario, will be fixed in VS 2017 update 1.

**Comment by JamesNK** [comment]
I'm not able to repo it anymore either. I got the error when debugging `JsonConvertTests.ShouldNotPopulateReadOnlyEnumerableObjectWithNonDefaultConstructor`.
