### ISSUE TITLE
Support "keep-alive" testhost

### ISSUE THREAD

**Issue by genlu** [Microsoft/vstest#611]
@saikrishnav did a spike on this before, we'd like to revive this discussion as part of the effort to improve perf.

**Comment by ManishJayaswal** [comment]
@sbaid FYI - It would be great to have this in next quarterly release.

**Comment by codito** [comment]
We definitely need data to take this decision. Perf savings v/s architecture mesh up.

The architecture mesh up part is because:
* Requirement for in-proc data collector is to run tests without appdomain. I am not sure if this is still a requirement. If it's not, things will be quite simple.
* Test host creates the appdomain on their behalf. This is required to ensure there is no locking of assemblies.
* Communication channel is loaded within the app domain created; i.e. it cannot stay up for more than one run. If we make communication layer move out, we will get into cross app domain calls (perf) and bunch of MarshalByRef problems very specific to full clr.

**Comment by ManishJayaswal** [comment]
@codito - how do you recommend we collect this data? Is there some prototype bits we can use? We can definitely measure the time we spend in creating the host every time but it seems like you are saying there will be some extra cost that may come in if we do the change.

**Comment by codito** [comment]
Yes, I think there will be cost due to marshalling and cross-appdomain calls if we implement keep-alive; it could be less/more than cost of creating a process + startup. @saikrishnav do we have the spike code around? Or did we measure this by any chance during spike?

**Comment by pvlakshm** [comment]
Closing this; reactivate if you think this is still relevant.
