### ISSUE TITLE
Running test with multiple xunit projects in a solution

### ISSUE THREAD

**Issue by couven92** [Microsoft/vstest#645]
In a solution with more than once XUnit test project, the Visual Studio test runner is only able to run the first xunit project in the solution. The xunit test runner then fails and prints the following to the test output:
> The active test run was aborted. Reason: Unable to communicate with test host process.

Installed XUnit packages (verfied as being the same version on both test projects):
```
Package: Microsoft.NET.Test.Sdk, Version: 15.0.0
Package: xunit, Version: 2.2.0
Package: xunit.runner.visualstudio, Version: 2.2.0
```

Visual Studio:
```
Microsoft Visual Studio Community 2017
VisualStudio/15.0.0-RTW+26228.4
```

.NET Core SDK: 
```
>dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

Installed .NET Core Runtime: `Version 1.1.1`

This issue was moved here from the original issue in the XUnit repository: https://github.com/xunit/xunit/issues/1174

**Comment by smadala** [comment]
@couven92 Thanks for logging issue. 
- Can you please share solution?
- What is output of `dotnet test` for Project2 project?

**Comment by jamesqo** [comment]
I am running into the same issue. Here is my solution: https://gitlab.com/jamesqo/PolynomialReducer/tree/256dca71fab1b6cf2faa0228d1f52897bc489443 Running `dotnet test` in the `PolynomialReducer.Tests` directory creates this output:

```
Build started, please wait...
...
Build completed.

Test run for C:\cygwin64\home\james\Code\cs\PolynomialReducer\PolynomialReducer.Tests\bin\Debug\netcoreapp1.0\PolynomialReducer.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
The active test run was aborted. Reason: Unable to communicate with test host process.
```

After the last message the runner seems to hang instead of exiting, so you have to press Ctrl+C to exit.

**Comment by smadala** [comment]
@jamesqo Looks like there are few tests causes `StackOverflowException` exception which is uncatchable. 
Ex: `PolynomialReducer.Tests.CompactR.PolynomialTests.Add_Polynomial_Polynomial` cause `StackOverflowException` at
https://gitlab.com/jamesqo/PolynomialReducer/blob/256dca71fab1b6cf2faa0228d1f52897bc489443/PolynomialReducer/CompactR/Polynomial.cs#L109. 

You can find exact exception location for other tests using `Debug Selected Tests` option from test explorer.

Use `dotnet test --diag log.txt`, To find reason why the test host process crashed. In this case you can see `TpTrace Error: 0 : 11784, 11, 2017/04/10, 19:06:23.279, 2996625370039, vstest.console.dll, Test host exited with error: Process is terminated due to StackOverflowException.` in `log.txt` file. (Format: `Test host exited with error:\<reason>`)

We are tacking issue [here](https://github.com/Microsoft/vstest/issues/627), for better logging.

**Comment by smadala** [comment]
Closing this because no repro.
