### ISSUE TITLE
Enable CLI UT template for .NET core 2.0

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#666]
## Description
dotnet new mstest for the latest master branch build does not support `-f netcoreapp2.0`

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by sbaid** [comment]
@blackdwarf @morrisjoe @pvlakshm @livarcocc  I see that `dotnet new` behavior is different for templates. Web template support `-f netcoreapp1.0/1.1` whereas  console template support `-f netcoreapp2.0` only. 

This item is to change the behavior of `dotnet new mstest/xunit` to same as `dotnet new console` and only support `netcoreapp2.0` . Pl clarify.
@codito

**Comment by livarcocc** [comment]
There are no templates for web yet because the binaries are still being worked on.

cc @mlorbetske who owns the templates.

**Comment by codito** [comment]
Templates for `netcoreapp2.0` are already available in `dotnet new` (dotnet-cli downloaded from dotnet-cli/master). This issue is probably no-op.

Here's the source: https://github.com/dotnet/templating/blob/rel/vs2017/post-rtw/template_feed/Microsoft.DotNet.Test.ProjectTemplates.2.0/content/MSTest-CSharp/Company.TestProject1.csproj

**Comment by smadala** [comment]
dotnet cli: 2.0.0-preview1-005696 has netcoreapp2.0 templates. closing the issue.
