### ISSUE TITLE
Tracking down tests that are taking longer or hanging

### ISSUE THREAD

**Issue by davidfowl** [Microsoft/vstest#715]
Is there a way to print the currently executing test? Is there a way to get that information?

**Comment by smadala** [comment]
Unfortunately we don't have out of box solution.
We can achieve it using Inproc data collector. 
For that you need Inproc data collector dll and runsettings file.
I am attaching simple project source, dll and runsettings file. This simple data collector writes currently executing test name to temp file, you can tail the temp file for knowing which test is executing.
[InprocDataCollector.zip](https://github.com/Microsoft/vstest/files/919833/InprocDataCollector.zip).
```cs
using System;
using System.IO;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollector.InProcDataCollector;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.InProcDataCollector;

public class SimpleDataCollector : InProcDataCollection
{
    private readonly string fileName;

    /// <summary>
    /// Initializes a new instance of the <see cref="SimpleDataCollector"/> class.
    /// </summary>
    public SimpleDataCollector()
    {
        this.fileName = Path.Combine(Path.GetTempPath(), "inproctest.txt");
        File.Delete(fileName);
    }

    public void Initialize(IDataCollectionSink dataCollectionSink)
    {
        // Do Nothing
    }

    /// <summary>
    /// The test session start.
    /// </summary>
    /// <param name="testSessionStartArgs">
    /// The test session start args.
    /// </param>
    public void TestSessionStart(TestSessionStartArgs testSessionStartArgs)
    {
        File.WriteAllText(this.fileName, "TestSessionStart : " + testSessionStartArgs.Configuration + "\r\n");
    }

    /// <summary>
    /// The test case start.
    /// </summary>
    /// <param name="testCaseStartArgs">
    /// The test case start args.
    /// </param>
    public void TestCaseStart(TestCaseStartArgs testCaseStartArgs)
    {
        File.AppendAllText(this.fileName, "TestCaseStart : " + testCaseStartArgs.TestCase.DisplayName + "\r\n");
    }

    /// <summary>
    /// The test case end.
    /// </summary>
    /// <param name="testCaseEndArgs">
    /// The test case end args.
    /// </param>
    public void TestCaseEnd(TestCaseEndArgs testCaseEndArgs)
    {
        File.AppendAllText(this.fileName, "TestCaseEnd : " + testCaseEndArgs.DataCollectionContext.TestCase.DisplayName + "\r\n");
    }

    /// <summary>
    /// The test session end.
    /// </summary>
    /// <param name="testSessionEndArgs">
    /// The test session end args.
    /// </param>
    public void TestSessionEnd(TestSessionEndArgs testSessionEndArgs)
    {
        File.AppendAllText(this.fileName, "TestSessionEnd");
    }
}
```
```xml
<RunSettings>
<InProcDataCollectionRunSettings>
      <InProcDataCollectors>
          <InProcDataCollector friendlyName='Test Impact' uri='InProcDataCollector://Microsoft/TestImpact/1.0' assemblyQualifiedName='SimpleDataCollector, InprocDataCollector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'  codebase="C:\Users\samadala\Documents\visual studio 2017\Projects\InprocDataCollector\InprocDataCollector\bin\Debug\netcoreapp1.1\InprocDataCollector.dll">
              <Configuration>
                  <Port>4312</Port>
              </Configuration>
          </InProcDataCollector>
      </InProcDataCollectors>
</InProcDataCollectionRunSettings>
</RunSettings>
```

Please change codebase  value in `runsettings` file according to local file path.
Pass runsettings to dotnet test (`dotnet test -s <path_to_runsettings_file>`).

You can find currently executing test using ` Get-Content -Path "C:\Users\<username>\AppData\Local\Temp\inproctest.txt" -Wait`

I have tested this on 
dotnet --info
.NET Command Line Tools (2.0.0-preview1-005448)

Product Information:
 Version:            2.0.0-preview1-005448
 Commit SHA-1 hash:  f8c3c4a030

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\samadala\src\vstest\tools\dotnet\sdk\2.0.0-preview1-005448\

In case you are interested in to find why testhost crahed, you can use  dotnet test --diag log.txt, 
Example log line in log.txt as follows:  `TpTrace Error: 0 : 11784, 11, 2017/04/10, 19:06:23.279, 2996625370039, vstest.console.dll, Test host exited with error: Process is terminated due to StackOverflowException`. (Format: Test host exited with error:\<reason>)

**Comment by davidfowl** [comment]
@smadala Can you guys add support for this please? Tracking down hanging tests takes longer than it needs to. Countless dev hours have been wasted on this. If there was a way to print the running test it would be trivial to find.

**Comment by smadala** [comment]
@codito @sbaid Should we add this to vstest backlogs?

**Comment by codito** [comment]
Yes, we should add this. cc: @pvlakshm. I'm wondering if this can be exposed as an argument to `dotnet test` or `vstest.console` e.g. `dotnet test --collect:progress`. Enabling the inproc collector support by default will cost performance (will increase chattyness too since each testcase result needs to flow between the runner and test host, today we batch the results).

@smadala the diagnostic logs don't have full stacktrace for crash?

**Comment by codito** [comment]
Similar request for test explorer is here: https://github.com/Microsoft/vstest/issues/627.

@pvlakshm will this fit into .netcore 2.0 theme in [vstest backlog](https://github.com/Microsoft/vstest/issues/686)?

**Comment by smadala** [comment]
> the diagnostic logs don't have full stacktrace for crash?

Diagnostic log file will have full stack trace in one line. 
Ex: `TpTrace Error: 0 : 23432, 8, 2017/04/14, 15:47:39.797, 36138705327, vstest.console.dll, Test host exited with error: Unhandled Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.   at testfail.UnitTest1.<>c.<OtherThreadFails>b__1_0() in C:\Users\samadala\tmp\testhosthang\UnitTest1.cs:line 18   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)`

**Comment by sbaid** [comment]
@davidfowl we are using partner-blocking label for issues are which are blocking partners. dogfood-impacting for issues which are impacting dogfooding but not blocking.

**Comment by davidfowl** [comment]
That sounds fine but doesn't give me an idea of where this lies in list of priorities for your team.

**Comment by sbaid** [comment]
@davidfowl backlog is [tracked here](https://github.com/Microsoft/vstest/issues?q=is%3Aopen+is%3Aissue+label%3Abacklog) . Can u pl share all the issues impacting in pri order?

**Comment by smadala** [comment]
@davidfowl From https://github.com/Microsoft/vstest/issues/623#issuecomment-287378175 xunit `longRunningTestSeconds` property can be used to find hanging/long running test.
By adding  `xunit.runner.json` to test dll directory with following content print it to console like `[xUnit.net 00:00:06.5689822] XUnitTestProject1: [Long Running Test] 'XUnitTestProject1.UnitTest1.Test1', Elapsed: 00:00:05`.
xunit.runner.json:
```json
{
  "diagnosticMessages": true,
  "longRunningTestSeconds": 2
}
```

**Comment by sbaid** [comment]
A helloworld [sample project](https://github.com/sbaid/samples/tree/master/XUnitNetCoreSample/XUnitNetCoreSample)

**Comment by sbaid** [comment]
@davidfowl Printing running test will only lead to suboptimal experience https://github.com/Microsoft/vstest/issues/301 xunit diagnostics are likely better to track down hung tests. This looks like the solution. 

Chat between runner & adapter for currently running tests will be prone to perf issues.

**Comment by codito** [comment]
Closing this issue since it is already supported by xunit adapter. Please reopen if it doesn't address the requirement.
