### ISSUE TITLE
dotnet test --logger "trx" missing categories

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#805]
> From @antferreira 

## Description
.trx file generated by dotnet test don't have test categories information

## Steps to reproduce
Create a test project with test methods annotated with [TestCategory("foo")].
Run dotnet test --logger "trx"

## Expected behavior
.trx file with test categories information 

## Actual behavior
.trx file without test categories information

## Environment
Windows 10 Pro 1607
MSTest.TestAdapter 1.1.17
MSTest.TestFramework 1.1.17
dotnet version 1.0.4

**Comment by AbhitejJohn** [comment]
I can repro this as well. Interestingly enough this data comes out fine in the log from Test Platform v1.

**Comment by Faizan2304** [comment]
From the following testing it seems that the bug is in MSTestV2.

| Test Platform | Adapter Version | Result |
| -------------- | ------------------ | ------- |
|     TPV2         |       MSTestV2     |  No TestCategory info in trx logger |
|     TPV1         |       MSTestV2     |  No TestCategory info in trx logger |
|     TPV2         |       MSTestV1     |  TestCategory info in trx logger |
|     TPV1         |       MSTestV1     |  TestCategory info in trx logger |


Closing this bug here and opening a new bug in testfx repo https://github.com/Microsoft/testfx/issues/189

**Comment by jayaranigarg** [comment]
Re-opening issue as this is a bug on Platform side and not adapter. Refer testfx issue for detailed findings.

**Comment by codito** [comment]
Closed as we're fixing this in testfx
