### ISSUE TITLE
Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.discoveryengine.x86.exe still used when TPv2 is enabled

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/vstest#814]
(splitting from #811 as this seems a different issue.)

## Description
After I enabled TPv2 for desktop tests, VS still uses `Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.discoveryengine.x86.exe` to discover tests

## Steps to reproduce
1. Enable TPv2 by following instructions at the bottom of https://github.com/Microsoft/vstest-docs/blob/master/docs/contribute.md#building-with-visual-studio.
2. Run `dotnet new xunit` to generate an xunit test project
3. Change the csproj to have the following content
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```
4. `dotnet restore`
5. Open the csproj in Visual Studio
6. Rebuild the project to trigger test discovery

## Expected behavior
discovery/execution engine from `Common7\IDE\CommonExtensions\Microsoft\TestWindow\` shouldn't be brought in.

## Actual behavior
Both of the following processes are spawn by VS, and the v1 discoveryengine is used, which caused same test failure in #811.

- `"C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.discoveryengine.x86.exe" /parentProcessId 7764`
- `"C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\TESTPLATFORM\vstest.console.exe" /parentprocessid:7764 /port:58197`

## Environment

Operating system: Windows 10: (a Microsoft internal selfhost version)

Visual Studio 2017 15.2

vstest.executionengine.x86.exe: 15.00.26228.0

**Comment by Faizan2304** [comment]
@jeremymeng : This is by design for now. We will remove it once we will fully move to TPV2. vstest.discoveryengine.x86.exe get spawned at the beginning irrespective of whether we are using TPV1 or TPV2 and it keep waiting for any communication with client. 

If target framework is net46 and TPV2 is not enabled through  testplatform.config ([detail info here](https://github.com/Microsoft/vstest-docs/blob/master/docs/contribute.md#running-tests-with-tpv2-using-test-explorer)) then only client (Test explorer) will use vstest.discoveryengine.x86.exe.
