### ISSUE TITLE
NUnit 3 test adapter (.NET Framework) reports tests twice

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/vstest#893]
## Description
When running tests via `VsTestConsoleWrapper`, the following callbacks are called:

1. `HandleDiscoveredTests(a bunch of tests)`
2. `HandleDiscoveryComplete(N, lastChunk: the same bunch of tests, isAborted: false)`

## Steps to reproduce
See #881 for repro cases and sample code. Based on the log files, this appears to be a bug in VSTest, not the adapter.

## Expected behavior
`HandleDiscoveredTests` is called with a bunch of tests
`HandleDiscoveryComplete` is called with a `lastChunk` of null.

## Actual behavior
`HandleDiscoveryComplete` is called with a `lastChunk` of previously-discovered tests.

## Environment
Using `Microsoft.TestPlatform` 15.0.0.0 from the MyGet feed.
Using NUnit3 test adapter 3.8.0-alpha1 from NuGet.
Windows 10 v1703

This behaviour does not occur with the same adapter for .NET Core.

**Comment by Faizan2304** [comment]
@yaakov-h I followed repro step but unfortunately I am not getting repro. 
Can you please share with us a repro code.

**Comment by yaakov-h** [comment]
Repro code at https://github.com/yaakov-h/VSTest893

Run `build.cmd`, then `run.cmd`.

The output I get from `run.cmd` is:

```
Running TestRunner for test assembly targeting .NET Framework 4.6...

Will test assembly that targets .NETFramework,Version=v4.6
Found extension NUnit3.TestAdapter.dll
HandleDiscoveryCompleted(totalTests: 1, lastChunk: [1 items], isAborted: False
Discovered 0 tests

Running TestRunner for test assembly tageting .NET Core 1.1...

Will test assembly that targets .NETCoreApp,Version=v1.1
Found extension NUnit3.TestAdapter.dll
HandleDiscoveredTests([1 items]
HandleDiscoveryCompleted(totalTests: 1, lastChunk: null, isAborted: False
Discovered 1 tests
  - TestProject.TestClass.TestMethod
```

Note that for .NET 4.6, `HandleDiscoveredTests` is never called, then `HandleDiscoveryCompleted` is called with a chunk.

For .NET Core 1.1, `HandleDiscoveredTests` is called with a chunk, then `HandleDiscoveryCompleted` is called with a null chunk.

**Comment by Faizan2304** [comment]
@yaakov-h : This behavior is not a bug but by design. The TestPlatform doesn't say that last chunk will be null. [See Sample Code](https://github.com/Microsoft/vstest/blob/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest/Program.cs#L206)

### Benefit of having last chunk in HandleDiscoveryCompleted
TestPlatform send HandleDiscoveredTests if number of discovered test is more than a particular size(default is 10 (and this is customizable through run setting)) or time elapsed from last call of HandleDiscoveryCompleted is more than 1.5 second [Code here](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Discovery/DiscoveryResultCache.cs#L128)

If any test left after above check we send it in last chunk of HandleDiscoveryCompleted [Code here](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Discovery/DiscoveryManager.cs#L124)

Now consider a scenario where there is only one tests in test project:
We need to call only one event of HandleDiscoveryCompleted with last chunk which will have one test. Now if we don't want to send test in last chunk then we have to make two call 
a) HandleDiscoveredTests with one test
b) HandleDiscoveryCompleted with last chunk null. 

### Why the behavior is different in case of netcore and net framework
This is due to internal implementation of how we run test for netcore test project.  You will see the same behavior if you will run .NET framework test with parallel enabled.

Can you please let me know what are the issue you are facing due to this behavior

**Comment by yaakov-h** [comment]
Hmm, that makes sense.

I tried increasing the number of tests and I'm still seeing a difference between netcore and netfx. netcore appears to always call `HandleDiscoveredTests` with the last chunk of tests, then `HandleDiscoveryCompleted` with null, whereas netfx appears to always call `HandleDiscoveredTests` without the final chunk, then `HandleDiscoveryCompleted` with the final chunk.

As you said, that's expected.

Unfortunately it seems that I cannot reproduce the behaviour I saw previously where `HandleDiscoveredTests` was called with the final chunk, then `HandleDiscoveryCompleted` was called with the same final chunk.

I'm closing this issue as I can't reproduce my own bug (:frowning_face:), I'll re-open if I see it again.
