### ISSUE TITLE
Running Debug Tests with no exceptions selected still breaks on exceptions

### ISSUE THREAD

**Issue by jkotalik** [Microsoft/vstest#985]
## Description
On the lastest preview build of VS 15.3, I am seeing visual studio break on exceptions being thrown even though in the exception settings all exceptions are disabled. 

## Steps to reproduce
I am currently running tests in https://github.com/aspnet/HttpAbstractions, with the command Test->Debug->All Tests, with all exceptions checked off for Break When Thrown.
## Expected behavior
Running Debug all tests should not break due to an exception being thrown

## Actual behavior
A few select exceptions are being breaked on (A System.IO exception and a System.FormatException).

## Environment
Running the latest preview build of VS2017 15.3 (version 26730.0.d15rel)

**Comment by Faizan2304** [comment]
Thank you @jkotalik for opening issue with us.
It seems odd to me ass well that visual studio break on exceptions being thrown even though in the exception settings all exceptions are disabled. 

I tried with console app and behavior is same over there as well, so it doesn't seems issue with testplatform. Its seems like it is the behavior of visual studio.

I will talk with team who owns debugger in Visual studio and will update the thread.

**Comment by Faizan2304** [comment]
@jkotalik 
I talked with team who owns debugger scenario and they said that `this is ‘by design’. The problem is that if the test framework catches an exception then the debugger sees an exception thrown in user code and caught in non-user code, so the exception is ‘user-unhandled’. User-unhandled isn’t controlled by the checkbox, but rather by this setting:`

![image](https://user-images.githubusercontent.com/19184362/29114084-c0ee7500-7d10-11e7-9d78-34b479319b94.png)

**The best work around:** when you stop on the exception the debugger will show you editor peak window. At the bottom of this there is a checkbox that says ‘Except when thrown from…’. Check that.

![image](https://user-images.githubusercontent.com/19184362/29114167-0755dd44-7d11-11e7-826a-071f0716e852.png)

**Comment by jkotalik** [comment]
Man that is a bit confusing! Thanks for the through investigation though. Maybe from a usability standpoint this should be changed. When I see that all checkboxes are off, I expect my code to not break for any exceptions, user-unhandled or not. For now I'll close this.
